### PR TITLE
types: privVal.LastSignature. closes #247

### LINKED ISSUE #247: Atomic privValidator.LastSignature
The fact that the PrivValidator object updates non-atomically with the vote being received by the state machine means there is a halt condition.

The halt condition was originally dealt with using replay/WAL (https://github.com/tendermint/tendermint/blob/master/consensus/replay_test.go#L59) - if we crash after signing a precommit but before we process it, we cannot recover because the PrivValidator won't let us sign again. Even with the current cswal, writing to PrivValidator is non-atomic with writing to the wal, so the halt can still happen if we crash after signing and before writing.

To fix this the PrivValidator should track the last thing signed and return that signature if the height/round/step match.

Also, I think there's also a bug in the PrivValidator.SignVote, namely, 
```
		if privVal.LastRound == vote.Round && privVal.LastStep > voteToStep(vote) {
			return errors.New("Step regression in SignVote")
		}
```

The `privVal.LastStep > voteToStep(vote)` means we could sign a precommit even if we already precommit. It should be `>=`.  Instead, let's make it:
```
	if privVal.LastRound == vote.Round {
		if privVal.LastStep > voteToStep(vote) {
			return errors.New("Step regression in SignVote")
		} else if privVal.LastStep == voteToStep(vote) {
			vote.Signature = privVal.LastSignature
		}
	}
```

EDIT: this issue used to consider eliminating the need for the WAL and moving catchup/replay to the DB. Instead, we'll just use a standard process to truncate the WAL.

### PR DESCRIPTION
**Pull request by ebuchman**
Coupled with the replay-WAL, this should prevent us from ever halting due to "losing a sig and not wanting to double sign".

### CODE REVIEW

File: consensus/replay.go [hunk 1]
```diff
@@ -53,31 +55,28 @@ func (cs *ConsensusState) readReplayMessage(msgBytes []byte, newStepCh chan inte
...
 				"hash", v.BlockHash, "header", v.BlockPartsHeader, "peer", peerKey)
 		}
-		// internal or from peer
-		if m.PeerKey == "" {
-			cs.internalMsgQueue <- m
-		} else {
-			cs.peerMsgQueue <- m
-		}
+
+		cs.handleMsg(m, cs.RoundState)
```
Comment (jaekwon) [inline consensus/replay.go]: was there a bug before where WAL entries would get duplicated?

File: consensus/replay_test.go [hunk 2]
```diff
@@ -56,43 +60,85 @@ var testLog = `{"time":"2016-04-03T11:23:54.387Z","msg":[3,{"duration":972835254
...
+	}
+
+	split := strings.Split(testLog, "\n")
+	lastMsg := split[nLines]
+
+	// we write those lines up to (not including) one with the signature
+	fileName := writeWAL(strings.Join(split[:nLines], "\n") + "\n")
 
 	cs := fixedConsensusState()
+	cs.QuitService.OnStart()
```
Comment (jaekwon) [inline consensus/replay_test.go]: I don't think we want to ever call OnStart() like this... shouldn't we just call Start()?  Just for consistency's sake.

Comment (jaekwon) [inline consensus/replay_test.go]: actually, i don't think we should even specify .QuitService. either, in case the service struct changes, no?

File: consensus/replay_test.go [hunk 3]
```diff
@@ -56,43 +60,85 @@ var testLog = `{"time":"2016-04-03T11:23:54.387Z","msg":[3,{"duration":972835254
...
 
 	// we've already precommitted on the first block
```
Comment (jaekwon) [inline consensus/replay_test.go]: these comments seem outdated?

File: consensus/replay_test.go [hunk 4]
```diff
@@ -104,3 +150,68 @@ func openWAL(t *testing.T, cs *ConsensusState, file string) {
...
+
+//-----------------------------------------------
+// Test the log at every iteration, and set the privVal last step
+// as if the log was written after signing, before the crash
+
+func TestReplayCrashAfterWrite(t *testing.T) {
+	split := strings.Split(testLog, "\n")
+	for i := 0; i < len(split)-1; i++ {
+		cs, newBlockCh, _, f := setupReplayTest(i+1, true)
+		runReplayTest(t, cs, f, newBlockCh)
```
Comment (jaekwon) [inline consensus/replay_test.go]: runReplayTest expects a new block.  Is it expected that all WAL prefixes (e.g. the first i lines for i := 0; i < len(split)) will generate new blocks?  Can we add a comment explaining why?  Cuz it isn't obvious to me.

File: consensus/replay.go (hunk 1 above)
Comment (ebuchman) [inline consensus/replay.go]: entries still get duplicated. we log before we even check if it applies.

File: consensus/replay_test.go (hunk 2 above)
Comment (ebuchman) [inline consensus/replay_test.go]: yeh i think this is a mistake. should be cs.Start().

File: consensus/replay_test.go (hunk 4 above)
Comment (ebuchman) [inline consensus/replay_test.go]: the block we wait for is just a signal that we haven't halted, its not necessarily something contained in the WAL itself. Assuming the consensus state is running, replay of any WAL, including the empty one, should eventually be followed by a new block, or else something is wrong

Comment (jaekwon) [inline consensus/replay_test.go]: oh cool, I think it would be nice to have that as a comment to explain the purpose of the test.

File: consensus/replay.go (hunk 1 above)
Comment (jaekwon) [inline consensus/replay.go]: it seems like it used to be more duplicated before: see https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L613 where we save to WAL and then call handleMsg

Comment (ebuchman) [inline consensus/replay.go]: we still do: https://github.com/tendermint/tendermint/blob/lastsig/consensus/state.go#L625

Comment (ebuchman) [inline consensus/replay.go]: oh, we used to also re-save logs during the replay, if that's what you're referring to, we no longer do that by not running the receiveRoutine and just calling handleMsg directly.

Comment (jaekwon) [inline consensus/replay.go]: yeah that's what i meant

**Comment by jaekwon** [comment]
looks good to me
