### PR TITLE
lite2: disconnect from bad nodes

### LINKED ISSUE #4385: lite2: disconnect from a node if it gives us bad header
If the light client receives a "bad" header (ValidateBasic fails or it's not signed by 1/3+), it needs to disconnect from the sender (this could be primary or any witness). If it's a primary, we replace it with a first witness and try to continue. If it's a witness, we simply remove it and continue. 

NOTE: we should not continue if there are no witnesses left! I.e. the light client should always check there's at least one witness left. Otherwise, exit.

@cmwaters could you please attach the picture from yesterday here?

### PR DESCRIPTION
**Pull request by melekes**
Closes #4385 

* [x] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [ ] ~~Updated CHANGELOG_PENDING.md~~

### CODE REVIEW

File: lite2/client.go [hunk 1]
```diff
@@ -603,14 +561,14 @@ func (c *Client) VerifyHeaderAtHeight(height int64, now time.Time) (*types.Signe
 // provider, provider.ErrSignedHeaderNotFound /
 // provider.ErrValidatorSetNotFound error is returned.
 func (c *Client) VerifyHeader(newHeader *types.SignedHeader, newVals *types.ValidatorSet, now time.Time) error {
-	c.logger.Info("VerifyHeader", "height", newHeader.Hash(), "newVals", fmt.Sprintf("%X", newVals.Hash()))
+	c.logger.Info("VerifyHeader", "height", newHeader.Height, "hash", hash2str(newHeader.Hash()), "vals", hash2str(newVals.Hash()))
```
Comment (golangcibot) [inline lite2/client.go]: line is 128 characters (from `lll`)

**Comment by melekes** [comment]
TODO:

- [ ] write a test

File: lite2/client_test.go [hunk 2]
```diff
@@ -743,7 +731,47 @@ func TestCompareWithWitnesses(t *testing.T) {
...
+		assert.Contains(t, err.Error(), "awaiting response from all witnesses exceeded dropout time")
+	}
+}
+
+func TestClientRemovesWitnessIfItSendsUsIncorrectHeader(t *testing.T) {
+	// straight invalid header
+	badProvider1 := mockp.New(
+		chainID,
+		map[int64]*types.SignedHeader{
+			3: &types.SignedHeader{Header: nil, Commit: nil},
```
Comment (golangcibot) [inline lite2/client_test.go]: File is not `gofmt`-ed with `-s` (from `gofmt`)
```suggestion
			3: {Header: nil, Commit: nil},
```

File: lite2/client_test.go [hunk 3]
```diff
@@ -743,7 +731,47 @@ func TestCompareWithWitnesses(t *testing.T) {
...
+		},
+		map[int64]*types.ValidatorSet{},
+	)
+
+	// less than 1/3 signed
+	badProvider2 := mockp.New(
+		chainID,
+		map[int64]*types.SignedHeader{
+			3: keys.GenSignedHeaderLastBlockID(chainID, 3, bTime.Add(1*time.Hour), nil, vals, vals,
+				[]byte("app_hash"), []byte("cons_hash"), []byte("results_hash"), len(keys), len(keys), types.BlockID{Hash: h2.Hash()}),
```
Comment (golangcibot) [inline lite2/client_test.go]: line is 123 characters (from `lll`)

File: lite2/client.go [hunk 4]
```diff
@@ -916,25 +879,35 @@ func (c *Client) backwards(toHeight int64, fromHeader *types.SignedHeader, now t
...
+			if err = altH.ValidateBasic(c.chainID); err != nil {
+				c.logger.Error("Witness sent us incorrect header", "err", err, "witness", witness)
+				witnessesToRemove = append(witnessesToRemove, i)
+				continue
+			}
+
+			if err = c.trustedNextVals.VerifyCommitTrusting(c.chainID, altH.Commit.BlockID,
+				altH.Height, altH.Commit, c.trustLevel); err != nil {
+				c.logger.Error("Witness sent us incorrect header", "err", err, "witness", witness)
+				witnessesToRemove = append(witnessesToRemove, i)
```
Comment (cmwaters) [inline lite2/client.go]: What happens if we notice double voting. Shouldn't we deal with that or should we just ignore it

Comment (cmwaters) [reply lite2/client.go]: actually why is this necessary. If I understand we are checking that there is a one third overlap between the next validator set at h + 1 and the witnesses current block at h.

Comment (melekes) [reply lite2/client.go]: https://github.com/tendermint/spec/pull/71#discussion_r374213456

Comment (cmwaters) [reply lite2/client.go]: okay no you are right because we haven't update trustedNextVals yet
