### PR TITLE
node: fix a bug where `nil` is recorded as node's address

### LINKED ISSUE #3716: Self node in addrbook.json and node tries to dial itself
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): `v0.31.7`

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://github.com/ndidplatform/smart-contract
It should also be reproducible with built-in or any ABCI apps.

**Environment**:
- **OS** (e.g. from /etc/os-release): Linux (Debian 9)
- **Install tools**:
- **Others**: TM in Docker container

**What happened**:
There’s a self node entry in `addrbook.json` and it tries to dial itself and fails.

**What you expected to happen**:
There shouldn't be an entry with self node ID in `addrbook.json` and it should not dial itself.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Run multiple nodes with PEX enabled.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
E[2019-06-04|06:01:19.260] dialing failed (attempts: 1): auth failure: secret conn failed: read tcp 172.20.0.5:38760->13.76.0.136:25000: read: connection reset by peer module=pex addr=f0f258b8b0dc09e0dde852600c1f13b4f65fe832@13.76.0.136:25000
E[2019-06-04|06:01:49.233] dialing failed (attempts: 2): auth failure: secret conn failed: EOF module=pex addr=f0f258b8b0dc09e0dde852600c1f13b4f65fe832@13.76.0.136:25000
E[2019-06-04|06:02:19.233] dialing failed (attempts: 3): auth failure: secret conn failed: EOF module=pex addr=f0f258b8b0dc09e0dde852600c1f13b4f65fe832@13.76.0.136:25000
E[2019-06-04|06:02:49.233] dialing failed (attempts: 4): auth failure: secret conn failed: read tcp 172.20.0.5:45554->13.76.0.136:25000: read: connection reset by peer module=pex addr=f0f258b8b0dc09e0dde852600c1f13b4f65fe832@13.76.0.136:25000
```

**Config (you can paste only the changes you've made)**:
```
external_address = "13.76.0.136:25000"

seeds = "a13b8622993d328e6020256113e6386726c95eb3@52.163.184.249:25000"
```

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

`addrbook.json`
```
{
	"key": "a188b4358bc4c60abaac6bf3",
	"addrs": [
		{
			"addr": {
				"id": "f0f258b8b0dc09e0dde852600c1f13b4f65fe832",
				"ip": "13.76.0.136",
				"port": 25000
			},
			"src": {
				"id": "a13b8622993d328e6020256113e6386726c95eb3",
				"ip": "52.163.184.249",
				"port": 25000
			},
			"attempts": 16,
			"last_attempt": "2019-06-05T00:19:19.233647509Z",
			"last_success": "0001-01-01T00:00:00Z",
			"bucket_type": 1,
			"buckets": [
				225,
				142,
				76
			]
		},
		{
			"addr": {
				"id": "82dac11a9b44a5a2eb1e3b2537f4c93e2e81fd49",
				"ip": "13.67.111.68",
				"port": 25000
			},
			"src": {
				"id": "a13b8622993d328e6020256113e6386726c95eb3",
				"ip": "52.163.184.249",
				"port": 25000
			},
			"attempts": 0,
			"last_attempt": "2019-06-04T06:01:19.258596546Z",
			"last_success": "0001-01-01T00:00:00Z",
			"bucket_type": 1,
			"buckets": [
				21,
				246,
				147
			]
		},
		{
			"addr": {
				"id": "a13b8622993d328e6020256113e6386726c95eb3",
				"ip": "52.163.184.249",
				"port": 25000
			},
			"src": {
				"id": "a13b8622993d328e6020256113e6386726c95eb3",
				"ip": "52.163.184.249",
				"port": 25000
			},
			"attempts": 0,
			"last_attempt": "2019-06-04T06:01:33.168053314Z",
			"last_success": "0001-01-01T00:00:00Z",
			"bucket_type": 1,
			"buckets": [
				152,
				15,
				4
			]
		},
		{
			"addr": {
				"id": "c8f4375561304d482e0226d4d244ba74f01fc042",
				"ip": "13.67.91.196",
				"port": 25000
			},
			"src": {
				"id": "c8f4375561304d482e0226d4d244ba74f01fc042",
				"ip": "13.67.91.196",
				"port": 25000
			},
			"attempts": 0,
			"last_attempt": "2019-06-04T06:01:38.720382132Z",
			"last_success": "0001-01-01T00:00:00Z",
			"bucket_type": 1,
			"buckets": [
				52,
				70,
				182
			]
		}
	]
}
```

`/status`
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "2"
      },
      "id": "f0f258b8b0dc09e0dde852600c1f13b4f65fe832",
      "listen_addr": "13.76.0.136:25000",
      "network": "test-chain-7eOWeY",
      "version": "0.31.7",
      "channels": "4020212223303800",
      "moniker": "b26a75d45568",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26000"
      }
    },
    "sync_info": {
      "latest_block_hash": "23EEA1FE2F79FA7E684F8B483F7D630B564627DCFFBC39447586222454C02A1E",
      "latest_app_hash": "90D0707E473FD2A4DDC640F11C94C33912BA8140B23FCE6A635766E33E9455E1",
      "latest_block_height": "126642",
      "latest_block_time": "2019-06-05T17:12:17.857901031Z",
      "catching_up": false
    },
    "validator_info": {
      "address": "8970757D071ABDB0B1F0E276234340E65798A636",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "aCmp1FTl1QPiugyjcLcRUpG7oH9qFrDgpKyFjUVQ1TU="
      },
      "voting_power": "10"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by melekes**
Solution

  `AddOurAddress` when we know it
  `sw.NetAddress` is `nil` in `createAddrBookAndSetOnSwitch`
  it's set by `n.transport.Listen` function, which is called during start

Fixes #3716

* [ ] ~~Updated all relevant documentation in docs~~
* [x] Updated all code comments where relevant
* [ ] Wrote tests
* [x] Updated CHANGELOG_PENDING.md

### CODE REVIEW

File: node/node.go [hunk 1]
```diff
@@ -441,17 +441,30 @@ func createSwitch(config *cfg.Config,
...
 
 func createAddrBookAndSetOnSwitch(config *cfg.Config, sw *p2p.Switch,
-	p2pLogger log.Logger) pex.AddrBook {
+	p2pLogger log.Logger, nodeKey *p2p.NodeKey) (pex.AddrBook, error) {
 
 	addrBook := pex.NewAddrBook(config.P2P.AddrBookFile(), config.P2P.AddrBookStrict)
 	addrBook.SetLogger(p2pLogger.With("book", config.P2P.AddrBookFile()))
 
 	// Add ourselves to addrbook to prevent dialing ourselves
-	addrBook.AddOurAddress(sw.NetAddress())
```
Comment (melekes) [inline node/node.go]: sw.NetAddress is nil at this point. It's populated by `transport#Listen`, which is called during `node#OnStart`
