### PR TITLE
state/privval: vote timestamp fix

### LINKED ISSUE #6738: state/privval: error adding vote (invalid signature) when continuing shutdown/start the node services.
Tendermint version: 0.34.11
ABCI app: N/A
Environment:
    OS: macOS 11.4 x86-64 

What happened:
When looking at the issue https://github.com/tharsis/ethermint/issues/140,

we found the issue occasionally happens due to shutdown/restart the local testnet (2 or 3 nodes) frequently.
Once the issue happens, the chain was halted and cannot be recovered.

This is part of logs when we're debugging the issue, it shows the node0 `signed and pushed vote` and then verifies failed at the following vote validation. See https://github.com/tendermint/tendermint/blob/master/internal/consensus/state.go#L2267-L2272

```
chainmaind-1/node0.log 10:50PM INF Replay: New Step height=70 module=consensus round=0 step=RoundStepPropose
chainmaind-1/node1.log 10:50PM DBG Received tick module=consensus new_ti={"duration":3000000000,"height":70,"round":0,"step":3} old_ti={"duration":-24031000,"height":70,"round":0,"step":1}
chainmaind-1/node0.log 10:50PM INF Replay: Proposal header={"hash":"A5F613E29237182D43D97DEB692CE7FB9548A0172A061A5909FBA12B817C3C45","total":1} height=70 module=consensus peer=local pol=-1 round=0
chainmaind-1/node1.log 10:50PM DBG Timer already stopped module=consensus
chainmaind-1/node0.log 10:50PM DBG Send channel=32 conn={"Logger":{}} module=p2p msgBytes=0A0408461803 peer={"id":"68d6899a1e53be6c129a07d77466e7bafb9718f6","ip":"::1","port":50204}
chainmaind-1/node1.log 10:50PM DBG Scheduled timeout dur=3000 height=70 module=consensus round=0 step=3
chainmaind-1/node0.log 10:50PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"3F833BCAB7220A41082C8FE7FA77605D0430A5FE9B7E182AF2BBCFE99725CEE3","parts":{"hash":"A5F613E29237182D43D97DEB692CE7FB9548A0172A061A5909FBA12B817C3C45","total":1}},"height":70,"pol_round":-1,"round":0,"signature":"l2FNuvW9F1l6wwGp5Fdoee24nM9Ze2orYuRKUTt6tzYcahMZ8hEzgO46l7IuPSe896DjUydbfCJfI9azUVquDw==","timestamp":"2021-07-16T02:50:37.782901Z"}
chainmaind-1/node1.log 10:50PM DBG Send channel=32 conn={"Logger":{}} module=p2p msgBytes=0A0408461803 peer={"id":"9aba27522b40341b93fe9c81275abba271ae48b5","ip":"::1","port":26650}
chainmaind-1/node0.log 10:50PM INF Replay: New Step height=70 module=consensus round=0 step=RoundStepPropose
chainmaind-1/node0.log 10:50PM INF Replay: Proposal header={"hash":"A5F613E29237182D43D97DEB692CE7FB9548A0172A061A5909FBA12B817C3C45","total":1} height=70 module=consensus peer=local pol=-1 round=0
chainmaind-1/node0.log 10:50PM INF Replay: BlockPart height=70 module=consensus peer=local round=0
chainmaind-1/node0.log 10:50PM INF received complete proposal block hash=3F833BCAB7220A41082C8FE7FA77605D0430A5FE9B7E182AF2BBCFE99725CEE3 height=70 module=consensus
chainmaind-1/node0.log 10:50PM DBG entering prevote step current=70/0/RoundStepPropose height=70 module=consensus round=0
chainmaind-1/node0.log 10:50PM DBG prevote step: ProposalBlock is valid height=70 module=consensus round=0
chainmaind-1/node0.log 10:50PM DBG signed and pushed vote height=70 module=consensus round=0 vote={"block_id":{"hash":"3F833BCAB7220A41082C8FE7FA77605D0430A5FE9B7E182AF2BBCFE99725CEE3","parts":{"hash":"A5F613E29237182D43D97DEB692CE7FB9548A0172A061A5909FBA12B817C3C45","total":1}},"height":70,"round":0,"signature":"Wr9QTqC1PAdH2F0LayeJZRzm8L9BLv5kWNLsEZhJzmf3k3CsVYWpP+Tg+0r3NSMLpquCRRrdXSRtIRSGGSPWCg==","timestamp":"2021-07-16T02:50:49.168977Z","type":1,"validator_address":"C001C6A1283A341C799E0FB7D4172689C68BCA26","validator_index":1}
chainmaind-1/node0.log 10:50PM DBG Broadcast channel=32 module=p2p msgBytes=0A0408461804
chainmaind-1/node0.log 10:50PM INF Replay: New Step height=70 module=consensus round=0 step=RoundStepPropose
chainmaind-1/node0.log 10:50PM INF Replay: Done module=consensus
chainmaind-1/node0.log 10:50PM DBG Send channel=32 conn={"Logger":{}} module=p2p msgBytes=0A0408461804 peer={"id":"68d6899a1e53be6c129a07d77466e7bafb9718f6","ip":"::1","port":50204}
chainmaind-1/node0.log 10:50PM INF Starting TimeoutTicker service impl=TimeoutTicker module=consensus
chainmaind-1/node0.log 10:50PM DBG Starting timeout routine module=consensus
chainmaind-1/node0.log 10:50PM DBG Attempt to update stats for non-existent peer module=consensus peer=
chainmaind-1/node0.log 10:50PM DBG Received tick module=consensus new_ti={"duration":3000000000,"height":70,"round":0,"step":3} old_ti={"duration":0,"height":0,"round":0,"step":0}
chainmaind-1/node0.log 10:50PM DBG Timer already stopped module=consensus
chainmaind-1/node0.log 10:50PM DBG Scheduled timeout dur=3000 height=70 module=consensus round=0 step=3
chainmaind-1/node0.log 10:50PM DBG Received tick module=consensus new_ti={"duration":-46110000,"height":70,"round":0,"step":1} old_ti={"duration":3000000000,"height":70,"round":0,"step":3}
chainmaind-1/node0.log 10:50PM DBG adding vote cs_height=70 module=consensus val_index=1 vote_height=70 vote_type=1
chainmaind-1/node0.log 10:50PM INF failed attempting to add vote err="failed to verify vote with ChainID chainmaind-1 and PubKey PubKeyEd25519{439DD8625A0F329D4F8D80C17CEA3CFFC01693F7DC518F692E1797024608E44B}: invalid signature" module=consensus
chainmaind-1/node0.log 10:50PM ERR failed to process message err="error adding vote" height=70 module=consensus msg={"Vote":{"block_id":{"hash":"3F833BCAB7220A41082C8FE7FA77605D0430A5FE9B7E182AF2BBCFE99725CEE3","parts":{"hash":"A5F613E29237182D43D97DEB692CE7FB9548A0172A061A5909FBA12B817C3C45","total":1}},"height":70,"round":0,"signature":"Wr9QTqC1PAdH2F0LayeJZRzm8L9BLv5kWNLsEZhJzmf3k3CsVYWpP+Tg+0r3NSMLpquCRRrdXSRtIRSGGSPWCg==","timestamp":"2021-07-16T02:50:49.168977Z","type":1,"validator_address":"C001C6A1283A341C799E0FB7D4172689C68BCA26","validator_index":1}} peer= round=0
```
After checked the voting logic, we suspect it might happen if we shut down the node is right after the `signVote` (in our case, it's in `FilePV`), the privval will store the latest sign data. See https://github.com/tendermint/tendermint/blob/68ffe8bc64e4efc8b50ee9ad2b857cecd0ca6c8d/privval/file.go#L353

And then we restarted the testnet, it falls into the replay process. The node will check the block proposal and try to vote it again.
However, I suspect this line only update the `Signature` but no `Timestamp`
https://github.com/tendermint/tendermint/blob/master/internal/consensus/state.go#L2219-L2220

So it causes the vote verification to fail later on. 
https://github.com/tendermint/tendermint/blob/68ffe8bc64e4efc8b50ee9ad2b857cecd0ca6c8d/types/vote_set.go#L203

What you expected to happen:
can add vote and chain is not halted after restarting the nodes.

Have you tried the latest version: 
No, but the voting logic looks like the same

Solution:
might need to update timestamp after this line.
https://github.com/tendermint/tendermint/blob/68ffe8bc64e4efc8b50ee9ad2b857cecd0ca6c8d/internal/consensus/state.go#L2220

Anything else we need to know: 
1. require to check the `signVote` logic in the other privval types if assign timestamp is the fix.
2. wal JSON file of node0 when reproducing the issue (just check the line after ENDHEIGHT 69)
https://drive.google.com/file/d/1F3Sz4tONd848RQya3WK94b9vWXHWyHTy/view?usp=sharing

### PR DESCRIPTION
**Pull request by JayT106**
Closes #6738

### CODE REVIEW

File: internal/consensus/common_test.go [hunk 1]
```diff
@@ -122,7 +123,21 @@ func (vs *validatorStub) signVote(
 	}
 	v := vote.ToProto()
 	err = vs.PrivValidator.SignVote(context.Background(), config.ChainID(), v)
+
+	// ref: signVote in FilePV, the vote should use the privious vote info when the sign data is the same.
+	if vs.lastVote != nil &&
```
Comment (williambanfield) [inline internal/consensus/common_test.go:128]: This if check is pretty long and it makes readability a bit difficult because it's hard to tell what its intention is from a glance. Can we wrap this in a helper function. Perhaps `signDataIsEqual(vote, vote) bool` that we can then use in this conditional.

File: internal/consensus/common_test.go [hunk 2]
```diff
@@ -122,7 +123,21 @@ func (vs *validatorStub) signVote(
...
+		vs.lastVote.Type == v.Type &&
+		bytes.Equal(vs.lastVote.BlockID.Hash, v.BlockID.GetHash()) &&
+		vs.lastVote.Height == v.GetHeight() &&
+		vs.lastVote.Round == v.Round &&
+		bytes.Equal(vs.lastVote.ValidatorAddress.Bytes(), v.GetValidatorAddress()) &&
+		vs.lastVote.ValidatorIndex == v.GetValidatorIndex() {
+		v.Signature = vs.lastVote.Signature
```
Comment (williambanfield) [inline internal/consensus/common_test.go:135]: Can `lastVote` ever be nil here?

File: internal/consensus/common_test.go (hunk 1 above)
Comment (alexanderbez) [reply internal/consensus/common_test.go:128]: ACK. Good idea!

**Review by alexanderbez — CHANGES_REQUESTED** [review]

File: internal/consensus/common_test.go (hunk 1 above)
Comment (JayT106) [reply internal/consensus/common_test.go:128]: sure. will update!

**Review by alexanderbez — APPROVED** [review]

**Review by williambanfield — APPROVED** [review]

**Review by cmwaters — APPROVED** [review]

**Comment by tessr** [comment]
Should this be backported to the 0.34 release branch?

**Comment by cmwaters** [comment]
Yeah I don't see any harm in backporting it to 0.34
