### PR TITLE
version: revert version through ldflag only

### LINKED ISSUE #6488: `/status` endpoint returns empty `version`
**Tendermint version**:
Tetsted with `v0.34.4`, `v0.34.5`, `v0.34.6`, `v0.34.7`, `v0.34.8`, `v0.34.9`, `v0.34.10`

**ABCI app**: 
Tendermint Docker file - No app

**Environment**:
Tendermint Docker

**What happened**:
When calling the `/status` endpoint the returned `node_info.version` is always empty if Tendermint version if `>= 0.34.4`

**What you expected to happen**:
The `node_info.version` should return either the Tendermint version or the checksum of the version

**Have you tried the latest version**: yes/no
Yes

**How to reproduce it** (as minimally and precisely as possible):
1. Start a Tendermint Docker container 
2. Query the `/status` endpoint

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

Add version back to versions, but allow it to be overridden via a ldflag.

Reason:

Many users are not setting the ldflag causing issues with tooling that relies on it (cosmjs)

closes #6488

cc @webmaster128

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -12,7 +12,7 @@ else
 VERSION := $(shell git describe)
 endif
 
-LD_FLAGS = -X github.com/tendermint/tendermint/version.TMCoreSemVer=$(VERSION)
+LD_FLAGS = -X github.com/tendermint/tendermint/version.Version=$(VERSION)
```
Comment (webmaster128) [inline Makefile:15]: What's the difference between this version and the hardcoded `TMCoreSemVer = "0.34.10"` below?

Is this an override mechanism or are those different versions?

Comment (webmaster128) [reply Makefile:15]: Found my answer in the description, sorry.

But then I am consused about the two differen terms "version" and "TMCoreSemVer"

Comment (marbar3778) [reply Makefile:15]: We can change the name, not married to "version"

Comment (webmaster128) [reply Makefile:15]: "version", "TMCoreSemVer" and "software" is used to refer to the same thing.

What about "tendermint version" consistently (in whatever spelling make sense)?

Comment (marbar3778) [reply Makefile:15]: version and tmCoreSemVer can't be the same tho

Comment (webmaster128) [reply Makefile:15]: Because of the override mechanism? Should then be `tmVersion` and `tmVersionDefault` to make clear this is the fallback for the same thing?

Comment (marbar3778) [reply Makefile:15]: yup, actually doing that now.

Comment (marbar3778) [reply Makefile:15]: as for software in the version struct, we will need to do this post 0.35 as we are trying to make 0.35 non breaking

Comment (webmaster128) [reply Makefile:15]: Yeah, sure. But still good to set a target name that should be adopted eventually. You can then comment it with

```
// This is the same as `tmVersion` and should be renamed when we get the chance
```

Comment (marbar3778) [reply Makefile:15]: opening an issue and adding it to a milestone instead. I dislike todos in the code.

Comment (marbar3778) [reply Makefile:15]: ref https://github.com/tendermint/tendermint/issues/6495

File: version/version.go [hunk 2]
```diff
@@ -3,12 +3,14 @@ package version
...
-	// TMCoreSemVer is the current version of Tendermint Core.
-	// It's the Semantic Version of the software.
-	TMCoreSemVer string
+	TMVersion = TMVersionDefault
 )
 
 const (
+
+	// TMCoreSemVer is the current version of Tendermint Core.
+	// It's the Semantic Version of the software.
```
Comment (cmwaters) [inline version/version.go:12]:
```suggestion
	// TMVersionDefault is the used as the fallback version of Tendermint Core
	// when not using git describe. It is formatted with semantic versioning.
```

File: CONTRIBUTING.md [hunk 3]
```diff
@@ -245,6 +245,7 @@ If there were no release candidates, and you'd like to cut a major release direc
      all PRs
    - Ensure that UPGRADING.md is up-to-date and includes notes on any breaking changes
       or other upgrading flows.
+   - Bump TMCoreSemVer version in  `version.go`
```
Comment (cmwaters) [inline CONTRIBUTING.md:248]:
```suggestion
   - Bump TMVersionDefault version in  `version.go`
```

File: CONTRIBUTING.md [hunk 4]
```diff
@@ -272,6 +273,7 @@ If there were no release candidates, and you'd like to cut a major release direc
      release, and add the github aliases of external contributors to the top of
      the changelog. To lookup an alias from an email, try `bash ./scripts/authors.sh <email>`
    - Reset the `CHANGELOG_PENDING.md`
+   - Bump TMCoreSemVer version in  `version.go`
```
Comment (cmwaters) [inline CONTRIBUTING.md:276]:
```suggestion
   - Bump TMVersionDefault version in  `version.go`
```

**Review by cmwaters — APPROVED** [review]
👍

**Comment by marbar3778** [comment]
@tessr as this mainly effects your work on releases, I'd like to get your sign off before merging.

**Review by tessr — APPROVED** [review]
LGTM, thank you! This should probably also get backported to 0.34.x, right?
