### PR TITLE
internal/blockchain/v0: prevent all possible race for blockchainCh.Out

### LINKED ISSUE #6516: blockchain/v0: possible data race/panic
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

1e0efb675899a9217d289db02c3f226b54e036c4

**What happened**:

Data race in Github Action with following command:

```
cat pkgs.txt.part.00 | xargs go test -mod=readonly -timeout 8m -race -coverprofile=00profile.out -covermode=atomic
```

https://github.com/tendermint/tendermint/pull/6509/checks?check_run_id=2708736360

**What you expected to happen**:

Test passed.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

It's hard to reproduce this consistently in local. But I can see possible problem through code review.

`r.processBlockchainCh`:

https://github.com/tendermint/tendermint/blob/7bf84d9d7f6f80a153e29cb4f1fd17b0d4264f1a/blockchain/v0/reactor.go#L159

and `r.processPeerUpdates`:

https://github.com/tendermint/tendermint/blob/7bf84d9d7f6f80a153e29cb4f1fd17b0d4264f1a/blockchain/v0/reactor.go#L160

are run in two separated goroutines. `r.processPeerUpdates` will call `r.processPeerUpdate`, which will send to `r.blockchainCh.Out`:

https://github.com/tendermint/tendermint/blob/7bf84d9d7f6f80a153e29cb4f1fd17b0d4264f1a/blockchain/v0/reactor.go#L317

While `r.processBlockchainCh` will close that channel:

https://github.com/tendermint/tendermint/blob/7bf84d9d7f6f80a153e29cb4f1fd17b0d4264f1a/blockchain/v0/reactor.go#L285

In summary, we send to a channel in a goroutine but close it in another one. That's exactly what the error in Github Action reports.

In the worst case, that would lead to a panic.

### PR DESCRIPTION
**Pull request by cuonglm**
This commit extends the fix in #6518, so all other goroutine which run
concurrently with processBlockchainCh can safely send data to blockchain
out channel via a bridge channel. This helps eliminating all possible
data race with sending and closing blockchainCh.Out channel at the same
time.

Fixes #6516

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em @marbar3778

**Review by tychoish — COMMENTED** [review]
it seems like this just renames an attribute in the reactor? how does it prevent races?

**Comment by cuonglm** [comment]
> it seems like this just renames an attribute in the reactor? how does it prevent races?

Not just rename, requestsRoutine is changed to send to bridge channel, instead of directly to blockchainCh.Out

**Comment by tychoish** [comment]
> Not just rename, requestsRoutine is changed to send to bridge channel, instead of directly to blockchainCh.Out

I see! I guess I'm not sure what the bug was before and how this solves it (or how the new channel gets registered. Also it was my understanding that keeping peer updates separate was useful, and this collapses that separation.

**Comment by cuonglm** [comment]
> > Not just rename, requestsRoutine is changed to send to bridge channel, instead of directly to blockchainCh.Out
> 
> I see! I guess I'm not sure what the bug was before and how this solves it (or how the new channel gets registered. Also it was my understanding that keeping peer updates separate was useful, and this collapses that separation.

Hmm, not collapse the separation. All tasks are still done in separated goroutines (processBlockchainCh, receiveRoutine, requestsRoutine). My very first version in #6518 merge the receiveRoutine into processBlockchainCh, and that what were concerned by @alexanderbez .

File: internal/blockchain/v0/reactor.go [hunk 1]
```diff
@@ -301,7 +306,7 @@ func (r *Reactor) processBlockchainCh() {
 				}
 			}
 
-		case envelop := <-r.peerUpdatesCh:
+		case envelop := <-r.blockchainOutBridgeCh:
```
Comment (alexanderbez) [inline internal/blockchain/v0/reactor.go:309]: I know this isn't an artifact of this PR, but can we quickly fix the spelling here please?

File: internal/blockchain/v0/reactor.go [hunk 2]
```diff
@@ -85,10 +85,15 @@ type Reactor struct {
...
 	fastSync    bool
 
-	blockchainCh  *p2p.Channel
-	peerUpdates   *p2p.PeerUpdates
-	peerUpdatesCh chan p2p.Envelope
-	closeCh       chan struct{}
+	blockchainCh *p2p.Channel
+	// blockchainOutBridgeCh is the bridge channel that other goroutine sending an Envelope to.
+	// processBlockchainCh will drain the Envelope from this channel and actually send it
+	// to blockchainCh.Out channel. This is necessary to prevent data race if other goroutine
```
Comment (alexanderbez) [inline internal/blockchain/v0/reactor.go:91]:
```suggestion
	// to blockchainCh.Out channel. This is necessary to prevent data race if other goroutines
```

File: internal/blockchain/v0/reactor.go [hunk 3]
```diff
@@ -85,10 +85,15 @@ type Reactor struct {
...
+	// send Envelope directly to blockchainCh.Out channel, since when processBlockchainCh may
```
Comment (alexanderbez) [inline internal/blockchain/v0/reactor.go:92]:
```suggestion
	// send an Envelope directly to the blockchainCh.Out channel, since when processBlockchainCh may
```

File: internal/blockchain/v0/reactor.go [hunk 4]
```diff
@@ -85,10 +85,15 @@ type Reactor struct {
...
+	// close the blockchainCh.Out at the time other goroutine send data to channel.
```
Comment (alexanderbez) [inline internal/blockchain/v0/reactor.go:93]:
```suggestion
	// closed, the blockchainCh.Out at the time other goroutine send data to the channel.
```

**Review by alexanderbez — CHANGES_REQUESTED** [review]
LGTM @cuonglm -- thank you. I just think we need to cleanup the field godoc a bit, but otherwise I think this is OK.

File: internal/blockchain/v0/reactor.go (hunk 4 above)
Comment (cuonglm) [reply internal/blockchain/v0/reactor.go:93]: Hmm, I don't understand this suggestion. What I mean is that the processBlockchainCh function may close the blockchainCh.Out channel at the same time other goroutines send data to it.

Comment (alexanderbez) [reply internal/blockchain/v0/reactor.go:93]: Yeah so the main point I want to get across is that the structure and grammar of this godoc for this field is a bit broken and hard to follow. Being that this change is critical to understand to the reader, it's imparitive that it's easy to understand as possible.

I suggest something like the following:

```go
// blockchainOutBridgeCh defines a channel that acts as a bridge between sending Envelope
// messages that the reactor will consume in processBlockchainCh and receiving messages
// from the peer updates channel and other goroutines. We do this instead of directly
// sending on blockchainCh.Out to avoid race conditions in the case where other goroutines
// send Envelopes directly to the to blockchainCh.Out channel, since processBlockchainCh
// may close the blockchainCh.Out channel at the same time that other goroutines send to
// blockchainCh.Out.
```

**Review by tychoish — APPROVED** [review]

**Review by alexanderbez — APPROVED** [review]

**Comment by alexanderbez** [comment]
Thanks @cuonglm. Let's get this branch rebased and we can merge :Thu

**Comment by odeke-em** [comment]
@cuonglm there is a merge conflict, please address it.

**Comment by cuonglm** [comment]
> @cuonglm there is a merge conflict, please address it.

Done
