### PR TITLE
light/rpc: fix ABCIQuery

### LINKED ISSUE #5106: light/rpc: implement abci_query
Currently, `ABCIQuery` and `ABCIQueryWithOptions` do not work (at least I don't think they do). Also, tests in `light/rpc/query_test.go` are all commented out. We should make the value proof format configurable so it can be checked and revamp the tests.

### PR DESCRIPTION
**Pull request by melekes**
Closes #5106

### CODE REVIEW

File: light/rpc/client.go [hunk 1]
```diff
@@ -104,28 +130,33 @@ func (c *Client) ABCIQueryWithOptions(ctx context.Context, path string, data tmb
...
+			return nil, errors.New("please configure Client with StoreNameRegexp option")
+		}
+		matches := c.storeNameRegexp.FindStringSubmatch(path)
+		if len(matches) != 1 {
+			return nil, fmt.Errorf("can't find store name in %s using %v", path, c.storeNameRegexp)
 		}
+		storeName := matches[0]
+
+		// 2) build a key path
 		kp := merkle.KeyPath{}
```
Comment (melekes) [inline light/rpc/client.go:144]: don't think this will work if key path is different...

Comment (melekes) [reply light/rpc/client.go:144]: this may be specific to cosmos SDK, but will not work for others

File: cmd/tendermint/commands/lite.go [hunk 2]
```diff
@@ -235,3 +242,23 @@ func saveProviders(db dbm.DB, primaryAddr, witnessesAddrs string) error {
...
+
+	return func(path string, key []byte) (merkle.KeyPath, error) {
+		matches := str.FindStringSubmatch(path)
+		if len(matches) != 1 {
+			return nil, fmt.Errorf("can't find store name in %s using %v", path, str)
+		}
+		storeName := matches[0]
+
+		kp := merkle.KeyPath{}
+		kp = kp.AppendKey([]byte(storeName), merkle.KeyEncodingURL)
```
Comment (melekes) [inline cmd/tendermint/commands/lite.go:260]: we should probably document this

**Comment by erikgrinaker** [comment]
This seems pretty tightly coupled to the SDK. Isn't this sort of functionality exposed via their gRPC server? Should we perhaps integrate with that instead?

File: cmd/tendermint/commands/lite.go [hunk 3]
```diff
@@ -39,6 +41,11 @@ need a primary RPC address, a trusted hash and height and witness RPC addresses
 (if not using sequential verification). To restart the node, thereafter
 only the chainID is required.
 
+When /abci_query is called, Cosmos SDK multistore Merkle key path format is used:
```
Comment (marbar3778) [inline cmd/tendermint/commands/lite.go:44]:
```suggestion
When /abci_query is called, the Merkle key path format is used:
```
? Not sure if it makes sense this way or mentioning the SDK

File: cmd/tendermint/commands/lite.go [hunk 4]
```diff
@@ -39,6 +41,11 @@ need a primary RPC address, a trusted hash and height and witness RPC addresses
...
+
+	/{store name}/{key}
+
+You may have a different format. Unfortunately, it can't be changed right now. Please consider forking the CLI.
```
Comment (marbar3778) [inline cmd/tendermint/commands/lite.go:48]: Does this part need to be user facing or application developer facing? 

We could say something like: "please verify with your application that this Merkle format is supported"?

File: light/rpc/client.go [hunk 5]
```diff
@@ -104,28 +134,28 @@ func (c *Client) ABCIQueryWithOptions(ctx context.Context, path string, data tmb
...
-		kp = kp.AppendKey([]byte(storeName), merkle.KeyEncodingURL)
-		kp = kp.AppendKey(resp.Key, merkle.KeyEncodingURL)
+
+		// 3) verify value
 		err = c.prt.VerifyValue(resp.ProofOps, l.AppHash, kp.String(), resp.Value)
 		if err != nil {
 			return nil, fmt.Errorf("verify value proof: %w", err)
 		}
-		return &ctypes.ResultABCIQuery{Response: resp}, nil
+	} else { // OR validate the ansence proof against the trusted header.
```
Comment (marbar3778) [inline light/rpc/client.go:152]:
```suggestion
	} else { // OR validate the absence proof against the trusted header.
```

File: cmd/tendermint/commands/lite.go (hunk 3 above)
Comment (cmwaters) [reply cmd/tendermint/commands/lite.go:44]: I second this: can't we spin it as a tendermint default key path that the cosmos sdk follows rather than the other way around

**Comment by marbar3778** [comment]
> This seems pretty tightly coupled to the SDK. Isn't this sort of functionality exposed via their gRPC server? Should we perhaps integrate with that instead?

I would propose the key format used in the sdk as our default because we do not have a full fledged app that we can test with, the Cosmos-SDK is our current alternative to simple testing with the kvstore. I do think applications, including the SDK, should call new client and add their own cli instead of using the one provided by Tendermint.

**Comment by cmwaters** [comment]
Looks good. Just a few minor comments. Do you want to rename the cmd/lite.go to cmd/light.go? And are we going to be able to uncomment the tests out in query_test.go?

**Comment by marbar3778** [comment]
I'm not sure this works, I observed an error when testing with the sdk: 

```
/cosmos.bank.v1beta1.Query/AllBalances <bytes.HexBytes Value> <int64 Value> <bool Value>]" returns="[<*coretypes.ResultABCIQuery Value> <error Value>]"
```

not sure if I should go to the SDK to debug or if this is from Tendermint

**Comment by marbar3778** [comment]
> I'm not sure this works, I observed an error when testing with the sdk:
> 
> ```
> /cosmos.bank.v1beta1.Query/AllBalances <bytes.HexBytes Value> <int64 Value> <bool Value>]" returns="[<*coretypes.ResultABCIQuery Value> <error Value>]"
> ```
> 
> not sure if I should go to the SDK to debug or if this is from Tendermint
> 
> full log:
> 
> ```
> I[2020-09-23|17:44:18.118] HTTPJSONRPC                                  method=abci_query args="[<*types.Context Value> /cosmos.bank.v1beta1.Query/AllBalances <bytes.HexBytes Value> <int64 Value> <bool Value>]" returns="[<*coretypes.ResultABCIQuery Value> <error Value>]"
> I[2020-09-23|17:44:18.118] Served RPC HTTP response                     method=POST url=/ status=200 duration=0 remoteAddr=127.0.0.1:57106
> ```
> 
> cmd:
> 
> ```
> gaiad query bank balances cosmos18v2cnwafyeqtp6y0w3vc4dvp7z3sfp22h7a9fj --node tcp://127.0.0.1:8888
> Error: RPC error -32603 - Internal error: can't verify value without a proof
> ```

submitting a tx also does not work

File: cmd/tendermint/commands/lite.go (hunk 3 above)
Comment (melekes) [reply cmd/tendermint/commands/lite.go:44]: yeah, we can rename to "ABCI default key path"

File: cmd/tendermint/commands/lite.go (hunk 4 above)
Comment (melekes) [reply cmd/tendermint/commands/lite.go:48]: user facing

**Comment by melekes** [comment]
> I'm not sure this works, I observed an error when testing with the sdk:

oops, sorry. this was because Prove=false was disallowed. changed it in https://github.com/tendermint/tendermint/pull/5375/commits/cfc8bc2eaffc31119e493f1bbdc208ac4243ee2c to always request proof independent of `Prove` flag

**Comment by melekes** [comment]
> This seems pretty tightly coupled to the SDK. Isn't this sort of functionality exposed via their gRPC server? Should we perhaps integrate with that instead?

The idea behind `abci_query` was to provide users a way to query application data without the need for application developers to expose RPC server by themselves (when Tendermint already has one). If Cosmos SDK and other ABCI apps? have chosen to expose the RPC server anyway (for some additional functionality), maybe we should consider stripping `/abci_query` from Tendermint and ABCI interface.

**Comment by cmwaters** [comment]
> The idea behind abci_query was to provide users a way to query application data without the need for application developers to expose RPC server by themselves (when Tendermint already has one).

Yeah this does seem like another thing that is more on the application side of the fence than tendermint so perhaps it's something where we should assume that either the cosmos-sdk or the application itself will handle. But in regards to the light client, won't this mean that applications will have to write their own light client logic on top if they want it to be able to query application state.

**Comment by melekes** [comment]
> won't this mean that applications will have to write their own light client logic on top if they want it to be able to query application state?

not if they use Cosmos SDK or have similar format.

**Review by cmwaters — APPROVED** [review]
lgtm 👍

**Comment by marbar3778** [comment]
LGTM 

It still doesn't work with the sdk, I get error: `Internal error: empty key or proof ops` which seems to be a SDK error now. I believe this is the closet we can get it on our side.

**Comment by melekes** [comment]
> It still doesn't work with the sdk, I get error: Internal error: empty key or proof ops which seems to be a SDK error now. I believe this is the closet we can get it on our side.

sounds like SDK did not provide a proof(s)

**Comment by melekes** [comment]
> do we want to add anything to the docs? I was thinking of an example of broadcasting a tx and then querying it afterwards on the light client page

light client RPC mirrors standard RPC completely. not sure we need to duplicate information, other than to say light client RPC will verify the result when possible.

> I personally am still a little bit fuzzy about how txs are saved and then can be found later on. This could also be elaborated in the Using Tendermint#Transactions section

On the tendermint side, we have https://docs.tendermint.com/master/rpc/#/Info/tx and /tx_search endpoints, which allow you to search for one or multiple transactions with their results (they work as long as the tx_indexer works).

On the app side, /abci_query exists. Its format is verify flexible and not really defined by Tendermint, except a few input parameters (path, data, etc.).

If you have ideas how to better structure this info, please open an issue.
