### PR TITLE
mempool: return duplicate tx errors more consistently

### LINKED ISSUE #7678: BroadcastTxCommit hangs if CheckTx returns non-zero code
**v0.35.0** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

https://github.com/ant1g/tendermint-built-in

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS BigSur 11.6
- **Install tools**: Golang v1.17.2
- **Others**:

**What happened**:
In the tendermint kvstore tutorial app, using the built-in deployment (ABCI app compiled with tendermint node), the BroadcastTxCommit function does not appear to behave properly.
First of, you can find in the repo url above an updated version of the kvstore tutorial app that works with the latest version of tendermint (v0.35.0), a PR is on the way to update the repo documentation.

If I submit a transaction that is rejected by the CheckTx function, the call will simply hang forever.
For example this will cause the hanging, as the validate function the ABCI app will expect a "=value" to be present and therefore the CheckTx will return non-zero code:
```
curl -s 'localhost:26657/broadcast_tx_commit?tx="tendermint"'
```

Where this works:
```
curl -s 'localhost:26657/broadcast_tx_commit?tx="tendermint=rocks"'
```

Additionally, re-running a previously successful transaction will also cause the BroadcastTxCommit to hang forever.
Run a second time:
```
curl -s 'localhost:26657/broadcast_tx_commit?tx="tendermint=rocks"'
```

**What you expected to happen**:

I expect the function call to return and to have the results of the CheckTx (check the non zero error code and the data field).
In the case of a replay of an old transaction, some special error code perhaps?

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Simply run the tutorial sample app with the latest version of tendermint, following the instructions in my repo (very simple).

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
I do see in the tendermint logs that the transaction is rejected, but nothing else:

```
2022-01-23T21:43:09+01:00 INFO rejected bad transaction code=1 module=mempool peer_id= post_check_err=null priority=0 tx=F6C3848FC2AB9188DD2C563828019BE7CEE4E269F5438C19F5173F79898E9EE6 version=v1
```

**Config (you can paste only the changes you've made)**:
The config is literally all defaults, apart from:
moniker = "node-0"
mode = "validator"

**node command runtime flags**:
N/A

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "round_state": {
      "height": "54",
      "round": 0,
      "step": 1,
      "start_time": "2022-01-23T20:44:45.14114Z",
      "commit_time": "2022-01-23T20:44:44.14114Z",
      "validators": {
        "validators": [
          {
            "address": "DB3788DC7D6EF8495ACF47B07BB34440CD4B0AC3",
            "pub_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "RUnvGtc5/xEs3g+4oDj8B57ZEWYyFB+OFKM1fiaC/dE="
            },
            "voting_power": "1",
            "proposer_priority": "0"
          }
        ],
        "proposer": {
          "address": "DB3788DC7D6EF8495ACF47B07BB34440CD4B0AC3",
          "pub_key": {
            "type": "tendermint/PubKeyEd25519",
            "value": "RUnvGtc5/xEs3g+4oDj8B57ZEWYyFB+OFKM1fiaC/dE="
          },
          "voting_power": "1",
          "proposer_priority": "0"
        }
      },
      "proposal": null,
      "proposal_block": null,
      "proposal_block_parts": null,
      "locked_round": -1,
      "locked_block": null,
      "locked_block_parts": null,
      "valid_round": -1,
      "valid_block": null,
      "valid_block_parts": null,
      "votes": [
        {
          "round": 0,
          "prevotes": [
            "nil-Vote"
          ],
          "prevotes_bit_array": "BA{1:_} 0/1 = 0.00",
          "precommits": [
            "nil-Vote"
          ],
          "precommits_bit_array": "BA{1:_} 0/1 = 0.00"
        }
      ],
      "commit_round": -1,
      "last_commit": {
        "votes": [
          "Vote{0:DB3788DC7D6E 53/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 2FF23F9A2697 97AC92893218 @ 2022-01-23T20:44:44.116922Z}"
        ],
        "votes_bit_array": "BA{1:x} 1/1 = 1.00",
        "peer_maj_23s": {}
      },
      "last_validators": {
        "validators": [
          {
            "address": "DB3788DC7D6EF8495ACF47B07BB34440CD4B0AC3",
            "pub_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "RUnvGtc5/xEs3g+4oDj8B57ZEWYyFB+OFKM1fiaC/dE="
            },
            "voting_power": "1",
            "proposer_priority": "0"
          }
        ],
        "proposer": {
          "address": "DB3788DC7D6EF8495ACF47B07BB34440CD4B0AC3",
          "pub_key": {
            "type": "tendermint/PubKeyEd25519",
            "value": "RUnvGtc5/xEs3g+4oDj8B57ZEWYyFB+OFKM1fiaC/dE="
          },
          "voting_power": "1",
          "proposer_priority": "0"
        }
      },
      "triggered_timeout_precommit": false
    },
    "peers": []
  }
}
```

**Anything else we need to know**:
N/A

### PR DESCRIPTION
**Pull request by tychoish**
Closes #7678

### CODE REVIEW

File: internal/mempool/mempool.go [hunk 1]
```diff
@@ -255,19 +255,12 @@ func (txmp *TxMempool) CheckTx(
 
 	txHash := tx.Key()
 
-	// We add the transaction to the mempool's cache and if the transaction already
-	// exists, i.e. false is returned, then we check if we've seen this transaction
-	// from the same sender and error if we have. Otherwise, we return nil.
+	// We add the transaction to the mempool's cache and if the
+	// transaction already exists, i.e. false is returned, then we
```
Comment (williambanfield) [inline internal/mempool/mempool.go:259]:
```suggestion
	// transaction is already present in the cache, i.e. false is returned, then we
```

**Review by creachadair — APPROVED** [review]

**Review by alexanderbez — APPROVED** [review]
