### PR TITLE
abci/server: print panic & stack trace to STDERR if logger is not set

### LINKED ISSUE #4382: Error and stack trace may be hidden in SocketServer if panic happen in ABCI app code.
Hi Tendermint team,

The commit a76c503dc666e438055d7147bfc6035526c6789c, PR: https://github.com/tendermint/tendermint/pull/3809 introduced the following change:
abci/server: recover from app panics in socket server.

Just to resume the changes, this introduce a recover in the handleRequests method of the abci SocketServer, if the application code panic, the panic is catched in the defer and recovered, then the error is sent to a goroutine through a channel, and the goroutine will log the error.

While this is a good thing in most case, the way it is implemented can be misleading when you need to debug a panic happening in your abc application, and in some case even completely hide the fact that a panic have occurred in user code (only the error would be logged)

This can lead to 2 issues:
- The default constructor (server.NewServer or server.NewSocketServer), build a server with a nil logger (which we did not realise before when using it) and the logger needs to be set explicitly via server.SetLogger. Which lead to the error not being logged at all if no logger is set.
- The stack trace of the panic is ignored in the recover and will not be printed.

I would suggest 2 fixes / changes:
- If the default logger is nil, then fallback to fmt.Println()
- Also retrieve the stacktrace at the time of the panic, and dump it either through fmt.Println or the logger if it’s not nil

For an example you can see how the http package is handling panic in user code: https://github.com/golang/go/blob/master/src/net/http/server.go#L1768-L1779
And the logf function falling back to fmt.Printf if the logger is nil: https://github.com/golang/go/blob/master/src/net/http/server.go#L3057-L3063

If these changes are acceptable I’m happy to send a pull request to implement them very soon.

Thanks.

### PR DESCRIPTION
**Pull request by melekes**
Closes #4382

### CODE REVIEW

File: abci/server/socket_server.go [hunk 1]
```diff
@@ -38,25 +42,25 @@ func NewSocketServer(protoAddr string, app types.Application) service.Service {
 		app:      app,
 		conns:    make(map[int]net.Conn),
 	}
-	s.BaseService = *service.NewBaseService(nil, "ABCIServer", s)
+	// Use standard logger by default.
+	logger := log.NewStdLibLogger(os.Stdout, "abci_server", stdlog.LstdFlags)
```
Comment (erikgrinaker) [inline abci/server/socket_server.go:46]: Let's not set a default logger, this breaks with conventions elsewhere in Tendermint. I think a simple `fmt.Printf()` call in the panic handler if the logger is `nil` should be sufficient, this is a last-ditch fallback more than anything.

Comment (melekes) [reply abci/server/socket_server.go]: Yeah, I agree. I'll make changes

File: abci/server/socket_server.go [hunk 2]
```diff
@@ -153,7 +153,12 @@ func (s *SocketServer) handleRequests(closeConn chan error, conn io.Reader, resp
 		// make sure to recover from any app-related panics to allow proper socket cleanup
 		r := recover()
 		if r != nil {
-			closeConn <- fmt.Errorf("recovered from panic: %v", r)
+			const size = 64 << 10
+			buf := make([]byte, size)
+			buf = buf[:runtime.Stack(buf, false)]
```
Comment (erikgrinaker) [inline abci/server/socket_server.go:158]: Clever

File: abci/server/socket_server.go [hunk 3]
```diff
@@ -153,7 +153,12 @@ func (s *SocketServer) handleRequests(closeConn chan error, conn io.Reader, resp
...
+			err := fmt.Errorf("recovered from panic: %v\n%s", r, buf)
+			stdlog.Println(err)
```
Comment (erikgrinaker) [inline abci/server/socket_server.go:160]: I think we only need to do this if `logger` is `nil`. I think output should also go to `stderr` instead of `stdout`, e.g. `fmt.Fprintf(os.Stderr, ...` or `log.New(os.StdErr).Printf(...)`

File: abci/server/socket_server.go [hunk 4]
```diff
@@ -153,7 +153,12 @@ func (s *SocketServer) handleRequests(closeConn chan error, conn io.Reader, resp
 		// make sure to recover from any app-related panics to allow proper socket cleanup
 		r := recover()
 		if r != nil {
-			closeConn <- fmt.Errorf("recovered from panic: %v", r)
+			const size = 64 << 10
```
Comment (erikgrinaker) [inline abci/server/socket_server.go:156]: Maybe just 65536?

Comment (melekes) [reply abci/server/socket_server.go:156]: no need
