### PR TITLE
blockchain/v0: fix data race in blockchain channel

### LINKED ISSUE #6516: blockchain/v0: possible data race/panic
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

1e0efb675899a9217d289db02c3f226b54e036c4

**What happened**:

Data race in Github Action with following command:

```
cat pkgs.txt.part.00 | xargs go test -mod=readonly -timeout 8m -race -coverprofile=00profile.out -covermode=atomic
```

https://github.com/tendermint/tendermint/pull/6509/checks?check_run_id=2708736360

**What you expected to happen**:

Test passed.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

It's hard to reproduce this consistently in local. But I can see possible problem through code review.

`r.processBlockchainCh`:

https://github.com/tendermint/tendermint/blob/7bf84d9d7f6f80a153e29cb4f1fd17b0d4264f1a/blockchain/v0/reactor.go#L159

and `r.processPeerUpdates`:

https://github.com/tendermint/tendermint/blob/7bf84d9d7f6f80a153e29cb4f1fd17b0d4264f1a/blockchain/v0/reactor.go#L160

are run in two separated goroutines. `r.processPeerUpdates` will call `r.processPeerUpdate`, which will send to `r.blockchainCh.Out`:

https://github.com/tendermint/tendermint/blob/7bf84d9d7f6f80a153e29cb4f1fd17b0d4264f1a/blockchain/v0/reactor.go#L317

While `r.processBlockchainCh` will close that channel:

https://github.com/tendermint/tendermint/blob/7bf84d9d7f6f80a153e29cb4f1fd17b0d4264f1a/blockchain/v0/reactor.go#L285

In summary, we send to a channel in a goroutine but close it in another one. That's exactly what the error in Github Action reports.

In the worst case, that would lead to a panic.

### PR DESCRIPTION
**Pull request by cuonglm**
There is a possible data race/panic between processBlockchainCh and
processPeerUpdates, since when we send to blockchainCh.Out in one
goroutine and close the channel in the other. The race is seen in some
Github Action runs.

This commit fix the race, by adding a peerUpdatesCh as a bridge between
processPeerUpdates and processBlockchainCh, so the former will send to
this channel, the later will listen and forward the message to
blockchainCh.Out channel.

Updates #6516

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em

**Comment by cmwaters** [comment]
I actually came across a similar situation when designing the PEX reactor and I wanted to merge the pex messages and the peer updates into a single thread to avoid a data race that I was observing. In the end however, we decided to keep with the design pattern of having separate go routines for peer updates and reactor messages and instead I used a mutex to avoid the race condition. I would assume we want to go down the same route here of just using a mutex but would like to here what @alexanderbez thinks about it

**Comment by cuonglm** [comment]
@cmwaters I don't think a mutex help here. The problem is that we sending to channel in a goroutine (peer updates) and close it in the other (process blockchain channel). You still face the issue that you send to a closed channel.

A possible solution is setting the channel to `nil` instead of closing it, so you can guard with a mutex then checking for channel is not nil before sending to it. I feel this lead to hard to read/maintain code than just merge the peer update and handle blockchain message to one goroutine.

**Comment by cuonglm** [comment]
Another instance https://github.com/tendermint/tendermint/runs/2717376714?check_suite_focus=true

**Comment by cmwaters** [comment]
I'm looking into it now. It would seem that we want to ensure that the peer update routine finishes before we close the blockchain channel. One way around it, although a bit messy, would be to have either a wait group or another `close` channel and just close the channels / routines sequentially, first the `peerUpdates` channel in the `processPeerUpdate()` routine and then the `blockchainCh` in the `processBlockChainCh()` routine

**Review by alexanderbez — CHANGES_REQUESTED** [review]
Thanks for catching this, but I'm a bit hesitant to approve this ATM.

I've spent careful time ensuring that all reactors follow the same patterns more or less with regards p2p Channel usage -- you'll see all reactors have `processPeerUpdates` and `handleMessage`, etc.

While I think this PR may fix the issue, it breaks consistency in design which I'd rather not do. Instead, can we possibly consider either:

1. Reversing the order of `<-r.peerUpdates.Done()` and `<-r.blockchainCh.Done()` in `OnStop` to ensure we don't send on a closed channel? OR
2. Use a `select` in `processPeerUpdate` when sending on `r.blockchainCh.Out`?

**Comment by cuonglm** [comment]
> Reversing the order of <-r.peerUpdates.Done() and <-r.blockchainCh.Done() in OnStop to ensure we don't send on a closed channel? OR

I don't think this solves problem:

 - OnStop() does `close(r.closeCh)`
 - This will signal `r.processBlockchainCh` and `r.processPeerUpdates` exits. The problem is that these functions are run in two separated goroutines,
 - Then there's still a chance that `r.processBlockchainCh` receives the exit signal, but `r.processPeerUpdates` receive peer update message at the same time, then if `r.processBlockchainCh` finish first, `r.processPeerUpdates` will send on a closed channel

> Use a select in processPeerUpdate when sending on r.blockchainCh.Out?

I'm not sure how it works, there's still a chance for race here.

If you want to keep the consistent design, I think the best solution is introducing a _bridge_ channel, something like `r.peerUpdateCh`, then `r.processPeerUpdate` will send to this channel instead of directly to `r.blockchainCh.Out`. Now `r.processBlockchainCh` will listen on this channel, and just send to `r.blockchainCh.Out` whenever a message available.

**Review by tychoish — APPROVED** [review]

**Comment by tychoish** [comment]
I don't have any large objection to this change, except: that it does mean that peer updates can block the processing of other requests. Which seems less than ideal. Having said that, in this case, the peer updates causes a send into the main channel for this reactor, which I think might be uncommon (wrt other reactors) and may warrant a change here.

**Comment by alexanderbez** [comment]
@cuonglm, yes, you're right about reversing the order during `OnStop`. Can you augment this PR to use a different pattern and remain consistent please?

**Comment by cuonglm** [comment]
@tychoish 

> I don't have any large objection to this change, except: that it does mean that peer updates can block the processing of other requests. Which seems less than ideal

Yay, if you read the PR description, you can see I mention this, too. Previously, the peer updates still block the processing of other requests, since when it also send to `blockchainCh.Out`.

**Comment by tychoish** [comment]
I just ran into this race condition in my PR, as a data point.

File: blockchain/v0/reactor.go [hunk 1]
```diff
@@ -298,6 +300,9 @@ func (r *Reactor) processBlockchainCh() {
 		case <-r.closeCh:
 			r.Logger.Debug("stopped listening on blockchain channel; closing...")
 			return
+
+		case envelop := <-r.peerUpdatesCh:
+			r.blockchainCh.Out <- envelop
```
Comment (alexanderbez) [inline blockchain/v0/reactor.go:305]: nit: can we put this case above the close case please?

**Review by alexanderbez — APPROVED** [review]

File: blockchain/v0/reactor.go (hunk 1 above)
Comment (cuonglm) [reply blockchain/v0/reactor.go]: Done

**Comment by tessr** [comment]
@cuonglm I believe if you update your branch again, it will now get auto-merged. Thanks for this patch!

**Comment by marbar3778** [comment]
does this also close #6005

**Comment by cuonglm** [comment]
> does this also close #6005

I think no, they're different problem.

**Comment by cuonglm** [comment]
> Hmm, looks like this still needs a rebase. It may also be that CI didn't pass, which is why it didn't get merged after an earlier rebase.

Yes, new change is added to master since my last rebase, rebased!
