### PR TITLE
separate mock evidence from real evidence

### LINKED ISSUE #2525: RegisterEvidences(cdc) currently registers mock evidence types
Currently register evidences is as follows:
```
func RegisterEvidences(cdc *amino.Codec) {
	cdc.RegisterInterface((*Evidence)(nil), nil)
	cdc.RegisterConcrete(&DuplicateVoteEvidence{}, "tendermint/DuplicateVoteEvidence", nil)

	// mocks
	cdc.RegisterConcrete(MockGoodEvidence{}, "tendermint/MockGoodEvidence", nil)
	cdc.RegisterConcrete(MockBadEvidence{}, "tendermint/MockBadEvidence", nil)
}
```
I think this will lead to unexpected behavior happening if people start submitting MockGoodEvidence, since we're currently supporting that. We should separate this into `RegisterEvidence` and `RegisterMockEvidence`.

### PR DESCRIPTION
**Pull request by melekes**
Closes #2525

* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

File: evidence/pool_test.go [hunk 1]
```diff
@@ -14,6 +15,13 @@ import (
 
 var mockState = sm.State{}
 
+func TestMain(m *testing.M) {
+	types.RegisterMockEvidences(cdc)
+
+	code := m.Run()
```
Comment (xla) [inline evidence/pool_test.go]: Why the extra assignment instead of passing `m.Run` straight to `os.Exit`?

Comment (melekes) [reply evidence/pool_test.go]: in my case it's easier to follow the execution path. in the case of `os.Exit(m.Run())`, the accent is shifted towards os.Exit, which should not be the case
