### PR TITLE
mempool: disable MaxBatchBytes

### LINKED ISSUE #5796: mempool: "weird stuff" when sending transaction batches
Reported via https://discord.com/channels/669268347736686612/669283915743232011/786256976724230215

> I have no idea what's actually happening inside the mempool, but something is very broken. In addition to the problem described above, I also observed internal mempool loops (transactions that are invalid being executed infinite times by checkTx), node disconnections (for bad behavior?) and weird stuff.

> I have reverted the @melekes PR on 0.34.0 and everything seems to go to normal: https://github.com/vocdoni/tendermint/tree/revert_batch_txs

### PR DESCRIPTION
**Pull request by melekes**
@p4u from vocdoni.io reported that the mempool might behave incorrectly under a
high load. The consequences can range from pauses between blocks to the peers
disconnecting from this node.

My current theory is that the flowrate lib we're using to control flow
(multiplex over a single TCP connection) was not designed w/ large blobs
(1MB batch of txs) in mind.

I've tried decreasing the Mempool reactor priority, but that did not
have any visible effect. What actually worked is adding a time.Sleep
into mempool.Reactor#broadcastTxRoutine after an each successful send ==
manual control flow of sort.

As a temporary remedy (until the mempool package
is refactored), the `max-batch-bytes` was disabled. Transactions will be sent
one by one without batching

Closes #5796

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -690,9 +690,6 @@ func (cfg *MempoolConfig) ValidateBasic() error {
 	if cfg.MaxBatchBytes < 0 {
```
Comment (p4u) [inline config/config.go:690]: IMO MaxBatchBytes must be also greater or equals to MaxTxBytes and since we know that MacBatchBytes higher than N creates a problematic behavior, Tehdernmint should at least print a Warning if MaxBatchBytes is set to a higher value by the user.

Note that with this default configuration, a Tx higher than 4KB would be never shared not received by any node.

**Comment by p4u** [comment]
I hope you are sure about this @melekes, you know Tendermint better than me, but this workaround looks like buring a very serious problem that eventually will be solved with a complete refactor in the future.

File: mempool/reactor.go [hunk 2]
```diff
@@ -271,19 +281,20 @@ func (memR *Reactor) broadcastTxRoutine(peer p2p.Peer) {
 // included.
 // WARNING: mutates next!
 func (memR *Reactor) txs(next *clist.CElement, peerID uint16, peerHeight int64) [][]byte {
-	batch := make([][]byte, 0)
+	batch := make([][]byte, 0, memR.config.MaxBatchBytes)
```
Comment (erikgrinaker) [inline mempool/reactor.go:284]: This can't be right? We're allocating a number of byte slices equal to `MaxBatchBytes`, so with e.g. 4096 we're allocating 4096 separate byte slices.

File: config/config.go (hunk 1 above)
Comment (erikgrinaker) [reply config/config.go:690]: Yeah, this isn't intuitive to me. The behavior here seems to be that we use the max of _either_ `MaxBatchBytes` or the largest tx in the mempool as the limit. Which means that if there is a tx of e.g. 1 MB in the mempool, then we'll send a 1 MB batch even though the user set the limit at 4 KB.

**Comment by erikgrinaker** [comment]
> My current theory is that the flowrate lib we're using to control flow

The rate limits are configurable. @p4u, can you see if increasing `send-rate` and `recv-rate` in `config.toml` to e.g. 10000000 (10 MB/s) improves the situation?

File: config/config.go (hunk 1 above)
Comment (melekes) [reply config/config.go]: > Note that with this default configuration, a Tx higher than 4KB would be never shared not received by any node.

nice catch! I was trying to come up with a way for batching to still work, but I guess it's better to disable it entirely.

**Comment by tessr** [comment]
> this workaround looks like buring a very serious problem that eventually will be solved with a complete refactor in the future

This is something we're trying to balance. Although we intend to do a complete refactor, it's not slated to begin for a few months, and it will probably take a few months itself. I think we're looking at mid-2021 before the mempool refactor is ready to roll. In the meantime, we'd like to see if there's a quick (but safe) fix that we can apply to get everything working for you again.

**Review by erikgrinaker — APPROVED** [review]
LGTM. I think the original PR that introduced this made some other changes as well, might be worth verifying that this change actually fixes the problems.

**Comment by p4u** [comment]
> This is something we're trying to balance. Although we intend to do a complete refactor, it's not slated to begin for a few months, and it will probably take a few months itself. I think we're looking at mid-2021 before the mempool refactor is ready to roll. In the meantime, we'd like to see if there's a quick (but safe) fix that we can apply to get everything working for you again.

Sure, I understand. I just wanted to point out that if the work around is not safe enough it would become a mess for anyone using Tendermint and upgrading to 0.34. If we are not sure of the safety of this, I'd revert the whole Batch Tx feature for now.

> fix that we can apply to get everything working for you again.

Well, not only for me but for anyone using Tendermint I hope :+1:

File: CHANGELOG_PENDING.md [hunk 3]
```diff
@@ -4,6 +4,12 @@
 
 Special thanks to external contributors on this release:
 
+@p4u from vocdoni.io reported that the mempool might behave incorrectly under a
+high load. The consequences can range from pauses between blocks to the peers
+disconnecting from this node. As a temporary remedy (until the mempool package
+is refactored), the `max-batch-bytes` was disabled. Transactions will be send
```
Comment (mvdan) [inline CHANGELOG_PENDING.md:10]: s/send/sent/

**Comment by tessr** [comment]
> I'd revert the whole Batch Tx feature for now. 

This is also on the table, if we can't implement a safe fix.

**Comment by tessr** [comment]
Is this PR description still accurate?

**Comment by melekes** [comment]
> Is this PR description still accurate, @melekes?

yes

**Review by alexanderbez — APPROVED** [review]
