### PR TITLE
state/kvindexer: associate event attributes with events

### LINKED ISSUE #9712: Unexpected results from block_search RPC
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.34.21

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
We noticed that sometimes hermes gets multiple blocks from `block_search` for a query that should have returned a single block. The exact query was:
```
"send_packet.packet_sequence='890' AND 
send_packet.packet_src_channel='channel-2' AND 
send_packet.packet_src_port='provider' AND 
send_packet.packet_dst_channel='channel-0' AND 
send_packet.packet_dst_port='consumer'"
```
The `block_search` was returning two blocks, one had something like:
```
"end_block_events": [
      {
        "type": "send_packet",
        "attributes": [
...
b'packet_sequence' b'890'
b'packet_src_port' b'provider'
b'packet_src_channel' b'channel-0'
b'packet_dst_port' b'consumer'
b'packet_dst_channel' b'channel-0'
...
	  ]
      },
      { =
        "type": "send_packet",
        "attributes": [
...
b'packet_sequence' b'884'
b'packet_src_port' b'provider'
b'packet_src_channel' b'channel-2'
b'packet_dst_port' b'consumer'
b'packet_dst_channel' b'channel-0'
...
	    ]
      }
]
```
(full  IBC events from `end_block_events` are [here](https://gist.github.com/ancazamfir/2e35c67d0dcda194bf834925e0a525ab))
This result seems to be wrong as the attributes span multiple `send_packet` types.

**What you expected to happen**:
If iiuc the block should be returned only if the attributes of an entry of the given type in the event list match the query. If my understanding is wrong please let me know. Also if the query can be formatted differently so we get the expected results.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
I added a simple [test](https://github.com/tendermint/tendermint/blob/211ebaf05264d10b82cbd4c22b485945d6e16e0b/state/indexer/block/kv/kv_test.go#L144) in `state/indexer/block/kv/kv_test.go`

### PR DESCRIPTION
**Pull request by jmalicevic**
Closes  #9712 

This PR changes the way keys are generated for block events, and how they are stored in the database. Namely,  
in previous versions, for each event attribute, there was a different entry in the kvstore. Users can query the events and get the corresponding height where an attribute occurred, but cannot correlate attributes to the actual events which they belong to. 

We expand the key with the event information, allowing a user to query for attributes that happened within the same height AND the same event. 

To achieve this behaviour, users have to add a `match_event=true` keyword to their RPC query. Otherwise, the index search system falls back to the original behaviour.

---

#### PR checklist

- [x] Tests written/updated, or no tests needed
- [x] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [x] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

File: state/txindex/kv/kv.go [hunk 1]
```diff
@@ -539,29 +554,47 @@ LOOP:
 // Keys
 
 func isTagKey(key []byte) bool {
-	return strings.Count(string(key), tagKeySeparator) == 3
+	// This should be always 4 if data is indexed together with event sequences
+	// The check for 3 was added to allow data indexed before (w/o the event number)
+	// to be retrieved. Note that this is no the cleanest solution, we should probably
+	// redesign this part.
+	numTags := strings.Count(string(key), tagKeySeparator)
+	return numTags == 4 || numTags == 3
```
Comment (jmalicevic) [inline state/txindex/kv/kv.go:562]: As stated this is potentially a hack. I believe though that the initial intuition here was that the tag keys (which I think are the keys in the query cannot be less than 3 items (key + height + event_type). Thus i deemed it acceptable that it is 3 or 4 to support old versions of the indexer. But people can disagree and we can forego adding event sequencing to the tx indexer.

**Comment by ancazamfir** [comment]
> To achieve this behaviour, users have to add a `match.event` keyword to their query. Otherwise, the index search system falls back to the original behaviour.

To clarify, if `match.events=1` is present in a query sent to an old tendermint version, the query will not behave like before. The implication for hermes is that it needs to format the query based on the version of the chain the query is sent to. We are trying to avoid this and wondering if there is a backwards compatible solution. 

On current version (without your changes) this returns two blocks:
```
http://provider-sentry-01.goc.earthball.xyz:27001/block_search?query="send_packet.packet_sequence='890' AND send_packet.packet_src_channel='channel-2'"
```
While this finds 0 blocks:
```
http://provider-sentry-01.goc.earthball.xyz:27001/block_search?query="send_packet.packet_sequence='890' AND send_packet.packet_src_channel='channel-2' AND match.events = 1"
```

cc @romac who brought this up: Is it possible to change the RPC to add an extra argument or option, something like:
`http://provider-sentry-01.goc.earthball.xyz:27001/block_search?query=_&page=_&per_page=_&order_by=_&match_events`
(with default `false` if new flag not present).

This currently works on old version and returns the two blocks:
```
http://provider-sentry-01.goc.earthball.xyz:27001/block_search?query="send_packet.packet_sequence='890' AND send_packet.packet_src_channel='channel-2'"&match_events=true"
```
Can we make it work within your PR branch? Or is this something that's already handled here? If it is, can you write one unit test for it?

**Comment by jmalicevic** [comment]
> To clarify, if `match.events=1` is present in a query sent to an old tendermint version, the query will not behave like before.

You are issuing the `match.events=1` to and old tendermint version that does not support this? That is probably why the result has 0 blocks. What I did preserve is that the new Tendermint version will be able to process data that was indexed with an old version but it will obviously not be able to differentiate between different events in that case. That is, the event identifier field will be set to the same value for any entry in the kvstore that was indexed w/o it.  But essentially you want to avoid older versions not returning anything when seeing the keyword. The only way I currently see to avoid this is making this behvaiour (with match.events=1 currently) default and having users explicitly use `match.events=0` if they want the old behaviour. This would not change the behaviour for old versions but users of a new version would have to be aware of this.

> This currently works on old version and returns the two blocks:


>http://provider-sentry-01.goc.earthball.xyz:27001/block_search?query="send_packet.packet_sequence='890' AND send_packet.packet_src_channel='channel-2'"&match_events=true" 

`match_events` should be with a `.` instead of `_` unless you internally parse it. On old versions however, this flag is basically ignored as it will always return two blocks - there is no way to know to which even an attribute belongs. 

I am currently running local tests using two TM versions to evaluate the behaviour of the indexer when upgrading from an old to a new version.

@ancazamfir an additional question, can you tell me whether you expect the same behaviour from the transaction indexer or is the block indexer your main concern?

**Comment by ancazamfir** [comment]
> [http://provider-sentry-01.goc.earthball.xyz:27001/block_search?query="send_packet.packet_sequence='890](http://provider-sentry-01.goc.earthball.xyz:27001/block_search?query=%22send_packet.packet_sequence=%27890)' AND send_packet.packet_src_channel='channel-2'"&match_events=true


> 

there was an extra `"`..i removed 

> match_events should be with a . instead of _ unless you internally parse it. On old versions however, this flag is basically ignored as it will always return two blocks - there is no way to know to which even an attribute belongs.

this is proposing a new flag, outside the query string. This would be a better solution for hermes as would work in a backwards compatible way.

> , can you tell me whether you expect the same behaviour from the transaction indexer or is the block indexer your main concern?

ah, I thought the problem is not present in the tx_indexer. I need to test this. will get back to you.

**Comment by jmalicevic** [comment]
@ancazamfir it is present and this PR has a solution for it too, but making it backwards compatible seems to be a bigger feat then I'd expected.

**Comment by jmalicevic** [comment]
As we allow multiple patch versions on the same network, this change, using a keyword not recognized by different minor versions is breaking the behaviour of old versions. I can change the implementation so that the default behaviour for nodes running new versions be that `match.events=1`. Old nodes won't be impacted by this. We'll have to discuss this  if this is sufficiently breaking that we want to put it in a major release.

**Comment by ancazamfir** [comment]
With the current hermes version we do not have the same issue for the `tx_search` as for `block_search` because it is always the case that packet messages for different IBC channels are sent in different Tx-es, with different hashes and indexes. This is also true for all other IBC messages.
This may change in the future but low prio for now.

The backwards compatibility aspect is very desirable though. Are you saying it is hard to add a new argument to the RPC query, outside the query string?

File: docs/app-dev/indexing-transactions.md [hunk 2]
```diff
@@ -145,6 +198,9 @@ You can query for a paginated set of transaction by their events by calling the
 ```bash
 curl "localhost:26657/tx_search?query=\"message.sender='cosmos1...'\"&prove=true"
 ```
+If the conditionsare related to transaction events and the user wants to make sure the
```
Comment (romac) [inline docs/app-dev/indexing-transactions.md:201]:
```suggestion
If the conditions are related to transaction events and the user wants to make sure the
```

**Review by thanethomson — COMMENTED** [review]
I didn't realize that this approach would involve adding methods to an `interface` (in this case the `SignClient` interface). As such it won't work to introduce this into v0.34, as that change is a breaking change.

There could be workarounds for that, but that would complicate this even further.

File: rpc/client/http/http.go [hunk 3]
```diff
@@ -501,6 +501,34 @@ func (c *baseRPCClient) TxSearch(
...
+	prove bool,
+	page,
+	perPage *int,
+	orderBy string,
+	matchEvents bool,
+) (*ctypes.ResultTxSearch, error) {
+	if matchEvents {
+		query = query + " AND match.events = 1"
+	}
+	return c.TxSearch(ctx, query, prove, page, perPage, orderBy)
```
[the remark this answers is not in the document]
Comment (jmalicevic) [reply rpc/client/http/http.go]: I kept the call to `TxSearch` with the change in the query syntax to avoid adding a new method to the `client`. We could have a `TxSearchMatchEvents` in the Client interface and implement it as you suggested afterwards. But this again introduces a method into the interface. We could also have the method here not in the client interface but just in the implementations that exist. But to me that is somehow not clean.

File: state/indexer/block/kv/kv.go [hunk 4]
```diff
@@ -95,11 +100,25 @@ func (idx *BlockerIndexer) Search(ctx context.Context, q *query.Query) ([]int64,
...
 	// (if it exists).
-	height, ok := lookForHeight(conditions)
-	if ok {
+	height, ok, heightIdx := lookForHeight(conditions)
+
+	// If we have additional constraints and want to query per event
+	// attributed, we cannot simply return all blocks for a height.
+	// But we remember the height we want to find and forward it to
+	// match()
+	if ok && (!matchEvents || (matchEvents && len(conditions) == 2)) {
```
Comment (sergio-mena) [inline state/indexer/block/kv/kv.go:121]: Please add to the comment that the check on the length of conditions being 2 is actually checking that there is no extra condition (2 = height + matchEvents)
... unless I'm getting it wrong

File: state/indexer/block/kv/kv.go [hunk 5]
```diff
@@ -318,6 +347,33 @@ LOOP:
 	return filteredHeights, nil
 }
 
+func (idx *BlockerIndexer) setTmpHeights(tmpHeights map[string][]byte, it dbm.Iterator, matchEvents bool) {
+	// If we return attributes that occur within the same events, then store the event sequence in the
+	// result map as well
+	if matchEvents {
+		eventSeq, _ := parseEventSeqFromEventKey(it.Key())
+		retVal := it.Value()
+		tmpHeights[string(append(retVal, byte(eventSeq)))] = it.Value()
```
Comment (sergio-mena) [inline state/indexer/block/kv/kv.go:356]: so what happens if there are more than 256 events in a height?

File: state/indexer/block/kv/kv.go [hunk 6]
```diff
@@ -437,8 +512,9 @@ func (idx *BlockerIndexer) match(
 
 	// Remove/reduce matches in filteredHeights that were not found in this
 	// match (tmpHeights).
-	for k := range filteredHeights {
-		if tmpHeights[k] == nil {
+	for k, v := range filteredHeights {
+		tmpHeight := tmpHeights[k]
+		if (tmpHeight != nil && !bytes.Equal(tmpHeights[k], v)) || tmpHeight == nil {
```
Comment (sergio-mena) [inline state/indexer/block/kv/kv.go:517]:
```suggestion
		if (tmpHeight != nil && !bytes.Equal(tmpHeight, v)) || tmpHeight == nil {
```

Comment (sergio-mena) [reply state/indexer/block/kv/kv.go:517]: ... actually, since Golang implements short circuit evaluation for `||`, you can simplify this condition like so:
```go
tmpHeight == nil || !bytes.Equal(tmpHeight, v)
```

File: state/indexer/block/kv/util.go [hunk 7]
```diff
@@ -74,24 +75,67 @@ func parseValueFromEventKey(key []byte) (string, error) {
...
+	if err != nil {
+		return 0, fmt.Errorf("failed to parse event key: %w", err)
+	}
+
+	// This is done to support previous versions that did not have event sequence in their key
+
 	if len(remaining) != 0 {
-		return "", fmt.Errorf("unexpected remainder in key: %s", remaining)
+		remaining, err = orderedcode.Parse(remaining, &eventSeq)
+		if err != nil || len(remaining) != 0 {
```
Comment (sergio-mena) [inline state/indexer/block/kv/util.go:116]: It's better to separate these conditions into two "if"s, because the error messages will be much clearer.
* If "err != nil" you will want to include the error in the message
* If remaining is not empty, you will want to the contents of remaining.
Besides, the error message can be clearer. Check lines 77-84 of the OLD version of this file (the version to the left of the diff)

File: state/txindex/kv/kv.go [hunk 8]
```diff
@@ -337,8 +367,26 @@ func (txi *TxIndex) match(
...
+			} else {
+				// If we have a particular height in the query, return only transactions
+				// matching this height.
+				if height != 0 {
+					eventHeight, err := extractHeightFromKey(it.Key())
+					if eventHeight != height || err != nil {
+						continue
+					}
+				}
+			}
```
Comment (sergio-mena) [inline state/txindex/kv/kv.go:387]:
```suggestion
			} else if height != 0 {
				// If we have a particular height in the query, return only transactions
				// matching this height.
				eventHeight, err := extractHeightFromKey(it.Key())
				if eventHeight != height || err != nil {
					continue
				}
			}
```

File: state/txindex/kv/kv.go [hunk 9]
```diff
@@ -419,8 +467,9 @@ func (txi *TxIndex) match(
 
 	// Remove/reduce matches in filteredHashes that were not found in this
 	// match (tmpHashes).
-	for k := range filteredHashes {
-		if tmpHashes[k] == nil {
+	for k, v := range filteredHashes {
+		tmpHash := tmpHashes[k]
+		if (tmpHash != nil && !bytes.Equal(tmpHashes[k], v)) || tmpHash == nil {
```
Comment (sergio-mena) [inline state/txindex/kv/kv.go:472]:
```suggestion
		if tmpHash == nil || !bytes.Equal(tmpHash, v) {
```

File: state/txindex/kv/kv.go [hunk 10]
```diff
@@ -454,8 +504,8 @@ func (txi *TxIndex) matchRange(
 	}
 
 	tmpHashes := make(map[string][]byte)
-	lowerBound := qr.LowerBoundValue()
-	upperBound := qr.UpperBoundValue()
+	// lowerBound := qr.LowerBoundValue()
+	// upperBound := qr.UpperBoundValue()
```
Comment (sergio-mena) [inline state/txindex/kv/kv.go:508]: Remove?

File: state/txindex/kv/kv.go [hunk 11]
```diff
@@ -520,8 +561,9 @@ LOOP:
 
 	// Remove/reduce matches in filteredHashes that were not found in this
 	// match (tmpHashes).
-	for k := range filteredHashes {
-		if tmpHashes[k] == nil {
+	for k, v := range filteredHashes {
+		tmpHash := tmpHashes[k]
+		if (tmpHash != nil && !bytes.Equal(tmpHashes[k], v)) || tmpHash == nil {
```
Comment (sergio-mena) [inline state/txindex/kv/kv.go:566]:
```suggestion
		if tmpHash == nil || !bytes.Equal(tmpHashes[k], v) {
```

File: state/txindex/kv/kv.go (hunk 1 above)
Comment (sergio-mena) [reply state/txindex/kv/kv.go:589]: Well, your comment is better than what I see on the left (no comment, so reader is forced to guess).
Also, consider removing the reference to this being "unclean", in any case, it seems to be the same solution as was before.

**Review by sergio-mena — COMMENTED** [review]
Wow, I wasn't aware of the complexity of this fix. Neat work!

File: abci/example/kvstore/persistent_kvstore.go [hunk 12]
```diff
@@ -142,7 +150,67 @@ func (app *PersistentKVStoreApplication) BeginBlock(req types.RequestBeginBlock)
 		}
 	}
 
-	return types.ResponseBeginBlock{}
+	response := types.ResponseBeginBlock{}
```
[the remark this answers is not in the document]
Comment (jmalicevic) [reply abci/example/kvstore/persistent_kvstore.go:153]: Ah I did not realise that the persistent one actually has a reference to the regular one. Yes, then this entire function can just call the non-persistent one.

File: state/indexer/block/kv/kv.go (hunk 4 above)
Comment (jmalicevic) [reply state/indexer/block/kv/kv.go:121]: That's correct. Done.

File: state/indexer/block/kv/kv.go (hunk 5 above)
Comment (jmalicevic) [reply state/indexer/block/kv/kv.go:357]: I completely overlooked that in Go `string()` will parse this to the ASCII value of  the int and it will wrap around if we get values bigger than 256:/ I will figure out how to change this. Nice catch, and many thanks!

Comment (jmalicevic) [reply state/indexer/block/kv/kv.go]: Should be fixed now.

File: state/indexer/block/kv/kv.go [hunk 13]
```diff
@@ -514,7 +514,7 @@ func (idx *BlockerIndexer) match(
 	// match (tmpHeights).
 	for k, v := range filteredHeights {
 		tmpHeight := tmpHeights[k]
-		if (tmpHeight != nil && !bytes.Equal(tmpHeights[k], v)) || tmpHeight == nil {
+		if (tmpHeight != nil && !bytes.Equal(tmpHeight, v)) || tmpHeight == nil {
```
Comment (sergio-mena) [inline state/indexer/block/kv/kv.go:518]:
```suggestion
		if tmpHeight == nil || !bytes.Equal(tmpHeight, v) {
```

File: state/txindex/kv/kv.go [hunk 14]
```diff
@@ -539,29 +577,51 @@ LOOP:
...
-	parts := strings.SplitN(string(key), tagKeySeparator, 3)
+	// numTags := strings.Count(string(key), tagKeySeparator)
+	parts := strings.SplitN(string(key), tagKeySeparator, -1)
 	return parts[1]
 }
 
-func keyForEvent(key string, value []byte, result *abci.TxResult) []byte {
-	return []byte(fmt.Sprintf("%s/%s/%d/%d",
+func extractEventSeqFromKey(key []byte) string {
+	// numTags := strings.Count(string(key), tagKeySeparator)
```
Comment (sergio-mena) [inline state/txindex/kv/kv.go:598]: ??

File: state/txindex/kv/kv.go [hunk 15]
```diff
@@ -539,29 +577,51 @@ LOOP:
...
+	return numTags == 4 || numTags == 3
 }
 
+func extractHeightFromKey(key []byte) (int64, error) {
+	parts := strings.SplitN(string(key), tagKeySeparator, -1)
+	return strconv.ParseInt(parts[2], 10, 64)
+}
 func extractValueFromKey(key []byte) string {
-	parts := strings.SplitN(string(key), tagKeySeparator, 3)
+	// numTags := strings.Count(string(key), tagKeySeparator)
```
Comment (sergio-mena) [inline state/txindex/kv/kv.go:592]: ??

File: state/indexer/block/kv/kv.go [hunk 16]
```diff
@@ -302,8 +328,12 @@ LOOP:
...
 	// Remove/reduce matches in filteredHashes that were not found in this
 	// match (tmpHashes).
-	for k := range filteredHeights {
-		if tmpHeights[k] == nil {
+	for k, v := range filteredHeights {
+		tmpHeight := tmpHeights[k]
+
+		// Check whether in this iteration we have not found an overlapping height (tmpHeight == nil)
+		// or whether the events in which the attributed occurred do not match (first part of the condition)
+		if (tmpHeight != nil && !bytes.Equal(tmpHeights[k], v)) || tmpHeight == nil {
```
Comment (sergio-mena) [inline state/indexer/block/kv/kv.go:336]:
```suggestion
		if tmpHeight == nil || !bytes.Equal(tmpHeight, v) {
```

**Review by sergio-mena — APPROVED** [review]
Thanks @jmalicevic for this nice work

File: rpc/core/blocks.go [hunk 17]
```diff
@@ -160,6 +160,23 @@ func BlockResults(ctx *rpctypes.Context, heightPtr *int64) (*ctypes.ResultBlockR
...
+	ctx *rpctypes.Context,
+	query string,
+	pagePtr, perPagePtr *int,
+	orderBy string,
+	matchEvents bool,
+) (*ctypes.ResultBlockSearch, error) {
+	// skip if block indexing is disabled
+	if _, ok := env.BlockIndexer.(*blockidxnull.BlockerIndexer); ok {
+		return nil, errors.New("block indexing is disabled")
+	}
```
Comment (thanethomson) [inline rpc/core/blocks.go:173]: Isn't this check already handled in the `BlockSearch` call?

File: rpc/core/tx.go [hunk 18]
```diff
@@ -133,3 +133,30 @@ func TxSearch(
...
+	matchEvents bool,
+) (*ctypes.ResultTxSearch, error) {
+
+	// if index is disabled, return error
+	if _, ok := env.TxIndexer.(*null.TxIndex); ok {
+		return nil, errors.New("transaction indexing is disabled")
+	} else if len(query) > maxQueryLength {
+		return nil, errors.New("maximum query length exceeded")
+	}
+
```
Comment (thanethomson) [inline rpc/core/tx.go:156]: Similar to my other comment: isn't this check already handled in the `TxSearch` call?

File: docs/app-dev/indexing-transactions.md [hunk 19]
```diff
@@ -177,5 +233,44 @@ You can query for a paginated set of blocks by their events by calling the
 curl "localhost:26657/block_search?query=\"block.height > 10 AND val_set.num_changed > 0\""
 ```
 
+## `match.events` keyword
```
Comment (thanethomson) [inline docs/app-dev/indexing-transactions.md:236]: Given that this is automatically added by way of the RPC flag, and we'll be changing the default behaviour to effectively have `match.events = 1` from Tendermint v0.37 onwards, should we be advertising this keyword in the docs?

It does, however, make sense to me to document the `match_events` RPC parameter though - please add this to the [OpenAPI spec](https://github.com/tendermint/tendermint/blob/v0.34.x/rpc/openapi/openapi.yaml)?

File: rpc/client/http/http.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (jmalicevic) [reply rpc/client/http/http.go]: Implementation changed, this function does not exist anymore.

File: state/indexer/block/kv/kv.go [hunk 20]
```diff
@@ -95,11 +100,27 @@ func (idx *BlockerIndexer) Search(ctx context.Context, q *query.Query) ([]int64,
...
+	// conditions to skip because they're handled before "everything else"
+	skipIndexes := make([]int, 0)
+
+	// Check whether we want to return heights where the conditions are true
+	// within the same event or it does not matter
+	matchEvents, matchEventIdx := lookForMatchEvent(conditions)
 
+	if matchEventIdx != -1 {
+		skipIndexes = append(skipIndexes, matchEventIdx)
+	}
```
Comment (thanethomson) [inline state/indexer/block/kv/kv.go:112]: What happens in this logic when someone submits a query like: `match.events=1 AND match.events=1 AND match.events=1`?

File: abci/example/kvstore/kvstore.go [hunk 21]
```diff
@@ -68,13 +68,20 @@ type Application struct {
...
+	// Should be false by default to avoid generating too much data.
+	genBlockEvents bool
 }
 
 func NewApplication() *Application {
 	state := loadState(dbm.NewMemDB())
 	return &Application{state: state}
 }
 
+func (app *Application) SetGenBlockEvents() {
```
Comment (thanethomson) [inline abci/example/kvstore/kvstore.go:81]: Is this method ever used anywhere?

Comment (jmalicevic) [reply abci/example/kvstore/kvstore.go:81]: This is not used atm but should be used if we want to turn on the generation of Blockevents.

File: state/indexer/block/kv/kv.go (hunk 20 above)
Comment (jmalicevic) [reply state/indexer/block/kv/kv.go:112]: You are right, same as @sergio-mena  [above](https://github.com/tendermint/tendermint/pull/9759#discussion_r1044869521). We should sanitize the query string and remove any occurences of `match.events`.  Actually it is very easy to ignore their occurrences in the code, but if someone were to enter `"match.events=1"&match_events=false`, the RPC values would be ignored. Will push a fix shortly.

File: docs/app-dev/indexing-transactions.md (hunk 19 above)
Comment (jmalicevic) [reply docs/app-dev/indexing-transactions.md:236]: I agree, I'll edit all the docs to not mention the match.events=1 keyword, rather just match the RPC.

File: rpc/core/tx.go (hunk 18 above)
Comment (jmalicevic) [reply rpc/core/tx.go:156]: It is. I figured, we can return from here immediately if these conditions are met to reduce a function call.

File: rpc/core/blocks.go [hunk 22]
```diff
@@ -171,8 +172,12 @@ func BlockSearchMatchEvents(
 	if _, ok := env.BlockIndexer.(*blockidxnull.BlockerIndexer); ok {
 		return nil, errors.New("block indexing (match events) is disabled")
 	}
+
+	re := regexp.MustCompile(`^match.events[" "]?=[" "]?[0-1]$|match.events[" "]?=[" "]?[0-1] AND | AND match.events[" "]?=[" "]?[0-1]`)
```
Comment (sergio-mena) [inline rpc/core/blocks.go:176]:
```suggestion
	re := regexp.MustCompile(`^match.events\s?=\s?[0-1]$|match.events\s?=\s?[0-1]\s+AND\s+|\s+AND match.events\s?=\s?[0-1]`)
```

Comment (sergio-mena) [reply rpc/core/blocks.go:176]: Also I think this justifies a couple extra UTs to test the regexp with weird values

Comment (thanethomson) [reply rpc/core/blocks.go:176]: Instead of using regular expressions, which are pretty brittle and could introduce a substantial performance hit, why not just deduplicate the `match.events` conditions from the parsed query conditions before this call: https://github.com/tendermint/tendermint/blob/4c549b582d4f713fde7d5d55fb7cf0618e633e0a/state/txindex/kv/kv.go#L225

File: rpc/core/tx.go (hunk 18 above)
Comment (thanethomson) [reply rpc/core/tx.go]: The function call is negligible in terms of practical impact. The practical impact of keeping these additional checks here is that they need to be kept in sync with the other checks (future developer effort).

I'd highly recommend removing them from both the `TxSearchMatchEvents` and `BlockSearchMatchEvents` methods and rather let the inner calls do the work.

File: rpc/core/blocks.go (hunk 22 above)
Comment (jmalicevic) [reply rpc/core/blocks.go:176]: Actually you read my mind, I changed this today but wanted to write a test or two to verify. Pushing this now.

File: state/indexer/block/kv/util.go [hunk 23]
```diff
@@ -74,24 +75,99 @@ func parseValueFromEventKey(key []byte) (string, error) {
...
+		}
+	}
+
+	return 0, false, -1
 }
 
-func lookForHeight(conditions []query.Condition) (int64, bool) {
-	for _, c := range conditions {
+func dedupHeight(conditions []query.Condition) (dedupConditions []query.Condition, height int64, found bool, idx int) {
+	found = false
```
Comment (thanethomson) [inline state/indexer/block/kv/util.go:137]:
```suggestion
```

The default for `bool` is `false`.

File: state/indexer/block/kv/util.go [hunk 24]
```diff
@@ -74,24 +75,99 @@ func parseValueFromEventKey(key []byte) (string, error) {
...
+	idx = -1
+	height = 0
```
Comment (thanethomson) [inline state/indexer/block/kv/util.go:139]:
```suggestion
```

The default for `int64` is `0`.

**Review by thanethomson — APPROVED** [review]
Excellent, thanks @jmalicevic! Great work! :tada: 

And thanks for adding in the extra unit tests :slightly_smiling_face:
