### PR TITLE
cli: fix abci help

### LINKED ISSUE #9693: abci-cli help command is broken
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 
0.38.0-dev

**ABCI app** (name for built-in, URL for self-written if it's publicly available): 
abc-cli

**Environment**:
- **OS** (e.g. from /etc/os-release): OSX
- **Install tools**: Installed from source
- **Others**:

**What happened**: 
Ran `abci-cli help` and `abc-cli help kvstore` and abci-cli tried to connect to a local socket, as per the snippet.

**What you expected to happen**: 
Help for `abci-cli` or for `kvstore` is shown

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Install abci-cli
Run abci-cli help kvstore

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```sh
{11:50}~/code/informal/tendermint/abci:9272-go-tutorials ✗ ➭ abci-cli help
I[2022-11-10|11:52:04.780] service start                                module=abci-client msg="Starting socketClient service" impl=socketClient
E[2022-11-10|11:52:04.780] abci.socketClient failed to connect to tcp://0.0.0.0:26658.  Retrying after 3s... module=abci-client err="dial tcp 0.0.0.0:26658: connect: connection refused"
^C
{11:52}~/code/informal/tendermint/abci:9272-go-tutorials ✗ ➭ abci-cli help kvstore
I[2022-11-10|11:52:14.344] service start                                module=abci-client msg="Starting socketClient service" impl=socketClient
E[2022-11-10|11:52:14.344] abci.socketClient failed to connect to tcp://0.0.0.0:26658.  Retrying after 3s... module=abci-client err="dial tcp 0.0.0.0:26658: connect: connection refused"
^C
```

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by JayT106**
Closes #9693

---

#### PR checklist

- [x] Tests written/updated, or no tests needed
- [x] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [x] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

File: abci/tests/test_cli/test.sh [hunk 1]
```diff
@@ -38,8 +38,34 @@ function testExample() {
...
+		diff "${INPUT}" "${INPUT}.new"
+		exit 1
+	fi
+
+	rm "${INPUT}".new
+}
+
 testExample 1 tests/test_cli/ex1.abci abci-cli kvstore
 testExample 2 tests/test_cli/ex2.abci abci-cli kvstore
+testHelp tests/test_cli/testHelp.out abci-cli help
```
Comment (sergio-mena) [inline abci/tests/test_cli/test.sh:68]: The broken command is `abci-cli help kvstore`.
To make sure, I've applied your patch, removed the change in `abci/cmd/abci-cli/abci-cli.go`, but left those in `test.sh` and the tests still pass.

**Review by sergio-mena — COMMENTED** [review]
Thanks for your patch!

**Comment by lasarojc** [comment]
If run without any commands, `abci-cli` returns the help message, which
lists **help** as a command.
Running `abci-cli help` fails, so I think the fix should be to either
remove the help command from the help message or make `abci-cli help`
perform the same as `abci-cli`.
As for help on other commands, they should be provided only through
`abci-cli command --help`

File: abci/cmd/abci-cli/abci-cli.go [hunk 2]
```diff
@@ -54,7 +54,7 @@ var RootCmd = &cobra.Command{
 	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
 
 		switch cmd.Use {
-		case "kvstore", "version":
+		case "kvstore", "version", "help [command]":
```
Comment (lasarojc) [inline abci/cmd/abci-cli/abci-cli.go:57]: Thanks for the patch, Jay.
This fixes the issue with the automatically generated help command reported.

File: abci/tests/test_cli/test.sh (hunk 1 above)
Comment (JayT106) [reply abci/tests/test_cli/test.sh:68]: in my local `abci-cli help` was also broken (basically, every help with a command is broken) before the patch, it will launch the abci_server. I will verify the test case without the patch again. Thanks for checking.

Comment (sergio-mena) [reply abci/tests/test_cli/test.sh:68]: NP, thanks for the help

**Review by lasarojc — APPROVED** [review]
Thanks, Jay. LGTM

File: abci/tests/test_cli/test.sh (hunk 1 above)
Comment (sergio-mena) [reply abci/tests/test_cli/test.sh:68]: You're right. I re-ran the same I did a few days ago (removing the fix, re-running the test, expecting it to fail) and it failed indeed.
I must have made a mistake when I did it the first time.
Sorry for the noise

**Review by sergio-mena — APPROVED** [review]
Many thanks!
