### PR TITLE
Normalise GenesisDoc before saving to state

### LINKED ISSUE #5986: `initialHeight == 0` not treated identically to `initialHeight == 1`
This change: https://github.com/tendermint/tendermint/pull/5191

Introduced support for an arbitrary `initialHeight` in genesis. The spec:

https://github.com/tendermint/spec/blob/master/rfc/002-nonzero-genesis.md

States:

>  A new field `initial_height` is added to the genesis file, defaulting to `1`. It can be set to any
non-negative integer, and `0` is considered equivalent to `1`.

However, currently this is not the case in the following code:

https://github.com/tendermint/tendermint/blob/master/state/execution.go#L348-L349

Here, if `initialHeight` is 0 then loading validators will throw. In Burrow we use a checkpointing mechanism that will replay the previous block during a crash, if we have a chain with just the initial block then `InfoSync` will announce block height 0 (which also has meaning for 'state restored' chains) and this line will get hit with `store.LoadValidators(0)` and fail. The old behaviour avoided this because it checked `block.Height > 1`

Here is my suggested fix: https://github.com/tendermint/tendermint/pull/5985

### PR DESCRIPTION
**Pull request by silasdavis**
Please feel free to close and replace this is more work or a better approach is needed, just opening to illustrate.

fixes #5986

### CODE REVIEW

**Comment by cmwaters** [comment]
Hey @silasdavis, thanks for the PR. This does seem to me like a more appropriate place to validate and complete the genesis doc. I will just check if there are any cases we might be missing.  It also feels like we are making this whole "get latest state or if none extract it from genesis" logic a lot more convoluted than perhaps it needs to be.

File: state/state.go [hunk 1]
```diff
@@ -335,11 +335,6 @@ func MakeGenesisDocFromFile(genDocFile string) (*types.GenesisDoc, error) {
 
 // MakeGenesisState creates state from types.GenesisDoc.
 func MakeGenesisState(genDoc *types.GenesisDoc) (State, error) {
-	err := genDoc.ValidateAndComplete()
```
Comment (melekes) [inline state/state.go:338]: I'd instead leave this because, if the state is partially gone (due to FS corruption or other reasons; `stateKey` is gone, but `genesisDocKey` is there, although the probability is very low), `LoadFromDBOrGenesisDoc` makes sure we always validate `genDoc`.

Comment (silasdavis) [reply state/state.go:338]: Yes why not. Two rights make a right.

**Review by melekes — APPROVED** [review]
👍
