### PR TITLE
consensus: don't panic when block is not found in store

### LINKED ISSUE #4069: Don't panic when block is not found in store
Tendermint currently crashes when the consensus reactor wants to help a peer catch up and send block parts which it does not hold in the store.

At Certus One we wipe the blockstore of some of our nodes to create small backups and allow quicker redeployments which is important to quickly react to events like DDoS or major outages. 

If a block is not found, the consensus reactor should not crash since this does not affect the ability to participate in consensus. Instead it should wait for the gossipSleepDuration and continue.

https://github.com/tendermint/tendermint/blob/288f1a0bc66499b71d688c80768a9e91173e0853/consensus/reactor.go#L503-L506

### PR DESCRIPTION
**Pull request by gregzaitsev**
* [X] Referenced an issue explaining the need for the change
* [X] Updated all relevant documentation in docs
* [X] Updated all code comments where relevant
* [ ] Wrote tests
* [x] Updated CHANGELOG_PENDING.md

Fixes #4069

### CODE REVIEW

File: consensus/reactor.go [hunk 1]
```diff
@@ -501,10 +501,14 @@ OUTER_LOOP:
...
 				blockMeta := conR.conS.blockStore.LoadBlockMeta(prs.Height)
 				if blockMeta == nil {
-					panic(fmt.Sprintf("Failed to load block %d when blockStore is at %d",
-						prs.Height, conR.conS.blockStore.Height()))
+					// Per issue 4069 comment: If a block is not found, the consensus reactor should not crash since 
+					// this does not affect the ability to participate in consensus. Instead it should wait for the 
+					// gossipSleepDuration and continue.
+					logger.Debug("Block not found in store", "height", prs.Height)
+					time.Sleep(conR.conS.config.PeerGossipSleepDuration)
+				} else {
```
Comment (marbar3778) [inline consensus/reactor.go]: I believe you can drop the else statement, otherwise LGTM

File: consensus/reactor.go [hunk 2]
```diff
@@ -501,10 +501,14 @@ OUTER_LOOP:
 			if prs.ProposalBlockParts == nil {
 				blockMeta := conR.conS.blockStore.LoadBlockMeta(prs.Height)
 				if blockMeta == nil {
-					panic(fmt.Sprintf("Failed to load block %d when blockStore is at %d",
-						prs.Height, conR.conS.blockStore.Height()))
+					// Per issue 4069 comment: If a block is not found, the consensus reactor should not crash since
```
Comment (marbar3778) [inline consensus/reactor.go]: This comment won't really help in the future, can it be reworded or removed

File: consensus/reactor.go (hunk 1 above)
Comment (melekes) [reply consensus/reactor.go]: no, we don't want to call InitProposalBlockParts with empty blockMeta

**Comment by melekes** [comment]
Could you please add an entry to `CHANGELOG_PENDING.md`?

```
BUGFIXES:
- [cs] \#4069 Don't panic when block meta is not found in store
```

File: consensus/reactor.go [hunk 3]
```diff
@@ -501,10 +501,12 @@ OUTER_LOOP:
 			if prs.ProposalBlockParts == nil {
 				blockMeta := conR.conS.blockStore.LoadBlockMeta(prs.Height)
 				if blockMeta == nil {
-					panic(fmt.Sprintf("Failed to load block %d when blockStore is at %d",
-						prs.Height, conR.conS.blockStore.Height()))
+					logger.Error("Failed to load block meta",
```
Comment (golangcibot) [inline consensus/reactor.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
					logger.Error("Failed to load block meta",
```

**Comment by hendrikhofstadt** [comment]
Awesome!

Any chance this could be backported to the tendermint version for the hub-3 (potential future patch release) so everyone can immediately profit from this?
