### PR TITLE
one less dependency

### LINKED ISSUE #2638: Remove ebuchman/fail-test dependency
We currently import ebuchman/fail-test in `consensus/state.go`, and `state/execution.go`. This repo is one small file, we should move it into tendermint.

### PR DESCRIPTION
**Pull request by zramsay**
closes #2638 

* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

File: libs/fail/fail.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
+package fail
+
+import (
+	"fmt"
+	"math/rand"
+	"os"
+	"strconv"
+)
+
+var callIndexToFail int
```
Comment (melekes) [inline libs/fail/fail.go]: note: we should probably rewrite this to avoid `callIndexToFail` being included in the runtime

File: libs/fail/fail.go [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+		Exit()
+	}
+
+	callIndex += 1
+}
+
+// FailRand should be called n successive times.
+// It will fail on a random one of those calls
+// n must be greater than 0
+func FailRand(n int) {
```
Comment (ebuchman) [inline libs/fail/fail.go]: We can just get rid of this func, it's never used.
