### PR TITLE
docker: fix incorrect time_iota_ms configuration

### LINKED ISSUE #4489: light: rpctest.Tendermint instance's clock drifts +7min
Discovered in: https://github.com/tendermint/tendermint/pull/4487

I think it's because we're stripping the monotonic part (see types/time/time.go) & using only a single instance (so not using medium time really). But it would be good to confirm this.

### PR DESCRIPTION
**Pull request by erikgrinaker**
Fixes the Docker problems discussed in #4489.

### CODE REVIEW

**Review by marbar3778 — COMMENTED** [review]
timeout_commit and iota were different and causing this?

**Review by marbar3778 — APPROVED** [review]
answered my own question by reading the issue. LGTM

File: DOCKER/docker-entrypoint.sh [hunk 1]
```diff
@@ -15,6 +15,7 @@ if [ ! -d "$TMHOME/config" ]; then
 			"$TMHOME/config/config.toml" &&
 		sed -i \
 			-e "s/^\s*\"chain_id\":.*/  \"chain_id\": \"$CHAIN_ID\",/" \
+			-e "s/^\s*\"time_iota_ms\":.*/  \"time_iota_ms\": \"500\"/" \
 			"$TMHOME/config/genesis.json"
```
Comment (webmaster128) [inline DOCKER/docker-entrypoint.sh:19]: Shouldn't we prefer `jq` to update a genesis file? This script will break as soon as time_iota_ms is not the last object entry anymore because of the missing trailing comma.

Comment (erikgrinaker) [reply DOCKER/docker-entrypoint.sh]: I was hoping no-one would notice. 😉 Updated now, thanks for the nudge!

Comment (webmaster128) [reply DOCKER/docker-entrypoint.sh]: 👨‍🏫

**Review by webmaster128 — APPROVED** [review]

**Review by melekes — APPROVED** [review]
👍
