### PR TITLE
p2p: persistent - redial if first dial fails

### LINKED ISSUE #1401: persistent peers doesnt work if we fail to connect the first time
If we fail to connect to a `persistent_peers` peer the first time, it seems we do not try to redial them right away until the addressbook suggests them during an ensurePeers call.

We should fix this so failure to connect the first time is treated the same as the connection being disconnected

### PR DESCRIPTION
**Pull request by tuxcanfly**
Fixes #1401

* [x] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by tuxcanfly** [comment]
Not sure if handshake failure should be handled too but my gut feeling says this is mainly for dial failures.

**Comment by tuxcanfly** [comment]
The tests are racy, a proper fix would probably require injecting the dialer to the functions.

File: p2p/peer.go [hunk 1]
```diff
@@ -87,6 +87,8 @@ func newPeer(pc peerConn, nodeInfo NodeInfo,
 type PeerConfig struct {
 	AuthEnc bool `mapstructure:"auth_enc"` // authenticated encryption
 
+	Dial func(addr *NetAddress, config *PeerConfig) (net.Conn, error)
```
Comment (melekes) [inline p2p/peer.go]: I'd rather not have functions inside config.

Comment (melekes) [reply p2p/peer.go]: maybe we can Have `badAddr`, which returns error on `DialTimeout`. This will require to inroduce NetAddress interface.

File: p2p/switch.go [hunk 2]
```diff
@@ -470,6 +476,7 @@ func (sw *Switch) addOutboundPeerWithConfig(addr *NetAddress, config *PeerConfig
 	peerConn, err := newOutboundPeerConn(addr, config, persistent, sw.nodeKey.PrivKey)
 	if err != nil {
 		sw.Logger.Error("Failed to dial peer", "address", addr, "err", err)
+		go sw.reconnectToPeer(addr)
```
Comment (ebuchman) [inline p2p/switch.go]: we only want to do this if the `persistent == true`

File: p2p/peer.go (hunk 1 above)
Comment (ebuchman) [reply p2p/peer.go]: I think better would be to set a flag on the remotePeer to allow it to reject the the connection in its accept routine. We should try to avoid putting methods in config structs like this

**Comment by ebuchman** [comment]
> Not sure if handshake failure should be handled too but my gut feeling says this is mainly for dial failures.

Yes we want any kind of connection failure on a persistent peer, dial or otherwise, to cause a reconnect attempt

**Comment by tuxcanfly** [comment]
@ebuchman I was wondering about what type of error would cause a handshake failure and would we want to have the same exponential backoff tracking as general failures (such as dial).

Talked to @jaekwon and he seemed to agree. I still need to read about the handshake process so I might be wrong.

File: p2p/switch.go (hunk 2 above)
Comment (tuxcanfly) [reply p2p/switch.go]: Done.

File: p2p/peer.go (hunk 1 above)
Comment (tuxcanfly) [reply p2p/peer.go]: Maybe we can have a the `Dial` func somewhere else? It seems more convenient to have a configurable dial behavior for testing, for e.g it could be used for slow connections / timeouts.

Comment (tuxcanfly) [reply p2p/peer.go]: Maybe `Switch`?

**Comment by kidinamoto01** [comment]
why is this PR still blocked?

**Comment by tuxcanfly** [comment]
@kidinamoto01 this it not ideal fix, I'm not sure if this even a complete fix since it doesn't handle handshake related errors (see comments above). I'll be closing this PR if that's OK, don't want to keep it lingering.

**Comment by kidinamoto01** [comment]
@tuxcanfly Thanks for the update, it's very helpful. Hope we can get this fixed soon O(∩_∩)O~

**Comment by ebuchman** [comment]
hey @tuxcanfly sorry for the delay here but I think you're right - we only want the reconnect on the dial, not on the handshake

**Comment by ebuchman** [comment]
On second thought, the handshake includes a timeout, which we might want to try again on, and even if we fail to connect due to compatibility issues, the remote persistent node might get restarted with correct software and then we can connect to it.

So I think unless we do more work on the typing of errors, its fine to just always run reconnectToPeer. Also note that in reconnectToPeer itself, we keep trying no matter what the error. Ill fix this up and merge, thanks!

**Comment by ebuchman** [comment]
Nope, what you've got is fine and straight forward. For now we'll only run the reconnect if we fail to dial the persistent peers. If we lost a connection though, we'll keep retrying even if eg the handshake fails

**Comment by ebuchman** [comment]
merged plus some minor changes: https://github.com/tendermint/tendermint/commit/0cbbb61962df84d1367c3f7da6e93638ae065819

**Comment by tuxcanfly** [comment]
Awesome! :100:
