### PR TITLE
Fix unsafe-reset-all for working with default home

### LINKED ISSUE #9102: `unsafe-reset-all` is not working with default home flag.
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

`0.34.19`

```
~/g/c/build release/v0.45.x > ./simd tendermint version
tendermint: v0.34.19
abci: 0.17.0
blockprotocol: 11
p2pprotocol: 8
```

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

N/A

**Environment**:
- OS: macOS v12.4
- Golang: 1.18.1

**What happened**:

Try to execute `<client> tendermint unsafe-reset-all`,
then the client try to delete `$HOME/data` directory.

**What you expected to happen**:
Tendermint should get default home directory but it can't.

**Have you tried the latest version**: yes/no
No

**How to reproduce it** (as minimally and precisely as possible):

1. Checkout `cosmos-sdk`(eb032e35b)
2. `make build`
3. `./build/simd init test`
4. `./build/simd tendermint unsafe-reset-all`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
~/g/c/build release/v0.45.x > ./simd tendermint unsafe-reset-all
I[2022-07-27|16:18:33.117] Removed all blockchain history               dir=/Users/rootwarp/data
I[2022-07-27|16:18:33.118] Reset private validator file to genesis state keyFile=/Users/rootwarp/config/priv_validator_key.json stateFile=/Users/rootwarp/data/priv_validator_state.json
```

**Config (you can paste only the changes you've made)**:
N/A

**node command runtime flags**:
N/A

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**
N/A

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by rootwarp**
Ref. #9102 
close #9102

`tendermint unsafe-reset-all` command should clear client's home directory
but this command is not working with default home flags.

Ad described #9102, `unsafe-reset-all` command try to clear `#HOME/data` directory by default
where is not client's home.

To resolve this issue, `ParseConfig` function explicitly get client's home
and set it into config.

### CODE REVIEW

**Review by cmwaters — COMMENTED** [review]
Thanks for the fix, could you rebase your PR against `main` instead of `v0.34.x`

**Comment by rootwarp** [comment]
> 

Fix :)

**Comment by rootwarp** [comment]
> Thanks for the fix, could you rebase your PR against `main` instead of `v0.34.x`

Fixed :)

File: cmd/tendermint/commands/root.go [hunk 1]
```diff
@@ -29,12 +29,20 @@ func registerFlagsRootCmd(cmd *cobra.Command) {
 
 // ParseConfig retrieves the default environment configuration,
 // sets up the Tendermint root and ensures that the root exists
-func ParseConfig() (*cfg.Config, error) {
+func ParseConfig(cmd *cobra.Command) (*cfg.Config, error) {
```
Comment (cmwaters) [inline cmd/tendermint/commands/root.go:32]: I think it would be better to pass just the home path string instead of the entire command.

Comment (cmwaters) [inline cmd/tendermint/commands/root.go:32]: It may be better to pass the home path string instead of an entire command but we can clean this up in a later PR

**Review by cmwaters — APPROVED** [review]
Looks great thanks!

File: cmd/tendermint/commands/root.go (hunk 1 above)
Comment (rootwarp) [reply cmd/tendermint/commands/root.go:32]: thx for your comment. I'll clean this up on next issue.

**Comment by cmwaters** [comment]
There seems to be a failure in one of the integration tests. I wonder if you need to let viper know the path to read the config from. Something like this:
```
func ParseConfig(cmd *cobra.Command) (*cfg.Config, error) {
        home, err := cmd.Flags().GetString(cli.HomeFlag)
	if err != nil {
		return nil, err
	}

	// name of config file (without extension)
	viper.SetConfigName("config")
	// search root directory
	viper.AddConfigPath(home)
	// search root directory /config
	viper.AddConfigPath(filepath.Join(home, defaultConfigDir))

        conf := cfg.DefaultConfig()
	err := viper.Unmarshal(conf)
	if err != nil {
		return nil, err
	}

	conf.RootDir = home
        ...
```

**Comment by rootwarp** [comment]
> There seems to be a failure in one of the integration tests. I wonder if you need to let viper know the path to read the config from. Something like this:
> 
> ```
> func ParseConfig(cmd *cobra.Command) (*cfg.Config, error) {
>         home, err := cmd.Flags().GetString(cli.HomeFlag)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	// name of config file (without extension)
> 	viper.SetConfigName("config")
> 	// search root directory
> 	viper.AddConfigPath(home)
> 	// search root directory /config
> 	viper.AddConfigPath(filepath.Join(home, defaultConfigDir))
> 
>         conf := cfg.DefaultConfig()
> 	err := viper.Unmarshal(conf)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	conf.RootDir = home
>         ...
> ```

Sorry my bad, I should to test before push PR.
I fixed code to pass test. `TMHOME` also should be accepted for home directory.
