### PR TITLE
light: use bisection (not VerifyCommitTrusting) when verifying a head…

### LINKED ISSUE #4934: lite2: use bisection (not VerifyCommitTrusting) when verifying a header from witness
When a fork is detected (two blocks have different hashes), we need to verify the one we got from a witness. Right now, we call `VerifyCommitTrusting`, which might fail if latestTrustedVals do not have 1/3+ presence in `altH.Commit`.

To properly verify an alternative header, we need to try to bisect from `latestTrustedHeader` to `altH`.

### PR DESCRIPTION
**Pull request by melekes**
…er from witness

When a fork is detected (two blocks have different hashes), we need to
verify the one we got from a witness. Right now, we call
VerifyCommitTrusting, which might fail if latestTrustedVals do not have
1/3+ presence in altH.Commit.

To properly verify an alternative header, we need to try to bisect from
latestTrustedHeader to altH.

Closes #4934

### CODE REVIEW

File: light/client.go [hunk 1]
```diff
@@ -737,43 +731,69 @@ func (c *Client) bisection(
...
-				c.logger.Error("Can't replace primary", "err", replaceErr)
-				// return original error
-				return fmt.Errorf("verify non adjacent from #%d to #%d failed: %w",
-					trustedHeader.Height, headerCache[depth].sh.Height, err)
-			}
-			newProviderHeader, newProviderVals, err := c.fetchHeaderAndValsAtHeight(newHeader.Height)
-			if err != nil {
-				return err
-			}
-			if !bytes.Equal(newProviderHeader.Hash(), newHeader.Hash()) || !bytes.Equal(newProviderVals.Hash(), newVals.Hash()) {
```
Comment (melekes) [inline light/client.go:761]: I think this is wrong. Old primary sent us invalid header. By requiring that invalid header == newProviderHeader, we essentially checking that newProviderHeader is invalid too!

**Comment by melekes** [comment]
let me see if I can quickly write a test case for that

File: light/client.go (hunk 1 above)
Comment (cmwaters) [reply light/client.go:761]: Hmm, here is my thinking, VerifyHeader isn't necessarily used to get the latest header but to verify any header and val set which may have not come from the primary provider, so when a primary provider is being replaced I thought we should check that we're bisecting towards the same untrusted header else there is no point in continuing. You are right that if we use `VerifyHeaderAtHeight` that we take the header from this "faulty" provider in which case we should restart - it kind of depends if we want to get the header at a certain height, or verify an existing header

Comment (cmwaters) [reply light/client.go:761]: In this implementation, if we were to do `VerifyHeaderAtHeight` it would return the header from the faulty provider and also an error:
```
err := fmt.Errorf("replacement provider has a different header: %X and/or vals: %X at height: %d"+
					"to the one being verified", newProviderHeader.Hash(), newProviderVals.Hash(), newHeader.Height)
```

which I think is okay - the user would just have to run it again with the new provider

Comment (melekes) [reply light/client.go:761]: hmm, I'm on the side of removing though - too much complexity already

Comment (cmwaters) [reply light/client.go:761]: if someone wanted to verify a provided header and we didn't have this case and completely restarted, the new provider could end up verifying a different header to the one initially requested to verify

Comment (cmwaters) [reply light/client.go:761]: sure I understand the complexity part - so would the light client just return an error if it came across an invalid header and had to swap out the primary provider?

Comment (melekes) [reply light/client.go:761]: I think in case where VerifyHeader(h) is called and h is invalid!, we should return the ErrHeaderInvalid immediately without trying to replace a provider

Comment (melekes) [reply light/client.go:761]: + we need the same check in sequence function. overwise, we don't know if we're verifying towards the same header

Comment (cmwaters) [reply light/client.go:761]: sure but I mean the case where we run `VerifyHeader(h)` and h may be valid but during the process of verification, the primary returns an invalid header

Comment (melekes) [reply light/client.go:761]: Okay, I reverted back the change. We can deal with this later in a separate PR.

File: light/client.go [hunk 2]
```diff
@@ -368,11 +368,6 @@ func (c *Client) initializeWithTrustOptions(options TrustOptions) error {
 		return fmt.Errorf("expected header's hash %X, but got %X", options.Hash, h.Hash())
 	}
 
-	err = c.compareNewHeaderWithWitnesses(h)
```
Comment (cmwaters) [inline light/client.go:371]: also don't forget to update the comment at the top of the function since we are no longer comparing with witnesses (btw I also agree that this is probably redundant)

File: light/client.go [hunk 3]
```diff
@@ -737,43 +727,79 @@ func (c *Client) bisection(
...
+				"newHash", newHeader.Hash(),
+				"newVals", newVals.Hash(),
+				"replHash", replacementHeader.Hash(),
+				"replVals", replacementVals.Hash())
+			// return original error
+			return err
+		}
+
+		// attempt to verify the header again
+		return c.bisection(c.primary, initiallyTrustedHeader, initiallyTrustedVals, replacementHeader, replacementVals, now)
```
Comment (cmwaters) [inline light/client.go:786]: I think this needs to be recursive i.e. change to `c.bisectionAgainstPrimary` else if there is a replacement of providers, the result of the verification with this new provider will be directly returned and won't be compared with the witnesses (also as a slightly minor case, we won't be able to replace the primary more than once per bisection)

File: light/client.go [hunk 4]
```diff
@@ -879,20 +905,64 @@ func (c *Client) updateTrustedHeaderAndVals(h *types.SignedHeader, vals *types.V
...
 }
 
-// fetch header and validators for the given height (0 - latest) from primary
-// provider.
-func (c *Client) fetchHeaderAndValsAtHeight(height int64) (*types.SignedHeader, *types.ValidatorSet, error) {
+// 0 - latest header
+// Note it swaps the primary with a witness if primary is not responding after
+// MaxRetryAttempts.
+func (c *Client) signedHeaderAndValSetFromPrimary(height int64) (*types.SignedHeader, *types.ValidatorSet, error) {
 	h, err := c.signedHeaderFromPrimary(height)
```
Comment (cmwaters) [inline light/client.go:912]: As an idea, it might be a lot cleaner if instead of having `c.signedHeaderFromPrimary` we had `c.signedHeaderFrom` and then we wouldn't need two functions for signedHeaderAndValSetFromPrimary and signedHeaderAndValSetFromWitness but just have `signedHeaderAndValSetFrom` pass the provider on to the new  created `c.signedHeaderFrom` - I don't know if you thought about this before but it may reduce the amount of code we need and make it cleaner - just an idea though

File: light/client.go [hunk 5]
```diff
@@ -879,20 +905,64 @@ func (c *Client) updateTrustedHeaderAndVals(h *types.SignedHeader, vals *types.V
...
+
+	c.providerMutex.Lock()
+	h, err := witness.SignedHeader(height)
+	c.providerMutex.Unlock()
+	if err != nil {
+		return nil, nil, fmt.Errorf("can't fetch header: %w", err)
 	}
+	err = c.validateHeader(h, height)
+	if err != nil {
+		return nil, nil, fmt.Errorf("invalid header: %w", err)
```
Comment (cmwaters) [inline light/client.go:936]: do you want to use the `InvalidHeader` error type for this case

File: light/client.go [hunk 6]
```diff
@@ -879,20 +905,64 @@ func (c *Client) updateTrustedHeaderAndVals(h *types.SignedHeader, vals *types.V
...
+	}
+
+	c.providerMutex.Lock()
+	vals, err := witness.ValidatorSet(height)
+	c.providerMutex.Unlock()
+	if err != nil {
```
Comment (cmwaters) [inline light/client.go:942]: Also the `no response` error type here

File: light/client.go [hunk 7]
```diff
@@ -1006,23 +1077,39 @@ func (c *Client) compareNewHeaderWithWitnesses(h *types.SignedHeader) error {
...
 		errc <- errBadWitness{err, noResponse, witnessIndex}
 		return
 	}
-
 	if err = altH.ValidateBasic(c.chainID); err != nil {
 		errc <- errBadWitness{err, invalidHeader, witnessIndex}
 		return
 	}
 
+	altVals, err := witness.ValidatorSet(h.Height)
```
Comment (cmwaters) [inline light/client.go:1092]: do you just want to use `c.signedHeaderAndValSetFromWitness` instead for these 4 functions

File: light/client.go (hunk 3 above)
Comment (melekes) [reply light/client.go:786]: good catch!

File: light/client.go (hunk 4 above)
Comment (melekes) [reply light/client.go:912]: I thought about it before. The difference between the two is signedHeaderFromPrimary does multiple retries and replaces primary on failures. signedHeaderFromWitness does not retry nor we need to replace it. I think this justifies two distinct functions

Comment (cmwaters) [reply light/client.go:912]: yeah I see, don't we do exponential backoff retries when we are requesting headers from witnesses (we just don't remove them)

**Comment by melekes** [comment]
> Do we need a changelog for this btw?

nah
