### PR TITLE
p2p/conn: FlushStop. Use in pex. Closes #2092

### LINKED ISSUE #2092: p2p: seed_mode sometimes fails to send pexAddrsMessage before disconnecting gracefully
When `SeedMode` is true, the PexReactor sends a batch of addresses and calls StopPeerGracefully. It seems sometimes the peer ends up disconnecting before these messages are delivered, which makes it difficult for a new node to join the network.

It looks like we don't call .flush() in the MConnection.OnStop(). I tried adding that on the seed node, but even still the new node sometimes fails to receive any addresses from the seed.

### PR DESCRIPTION
**Pull request by ebuchman**
In seed mode, we call StopPeer immediately after Send.
Since flushing msgs to the peer happens in the background,
the peer connection is often closed before the messages are
actually sent out. With FlushStop, we allow all msgs to first be written and flushed out
on the conn before it is closed.

This should be a proper solve for this issue, to replace https://github.com/tendermint/tendermint/pull/2797/files#diff-8c6b1a350a161ced01d68514ccda7484R224

Closes #2092 

* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

File: p2p/pex/pex_reactor_test.go [hunk 1]
```diff
@@ -40,7 +40,7 @@ func TestPEXReactorBasic(t *testing.T) {
 	assert.NotEmpty(t, r.GetChannels())
 }
 
-func TestPEXReactorAddRemovePeer(t *testing.T) {
+func TestPEXReactorAddRemoveneer(t *testing.T) {
```
Comment (melekes) [inline p2p/pex/pex_reactor_test.go]: typo?

```suggestion
TestPEXReactorAddRemovePeer
```

File: p2p/pex/pex_reactor.go [hunk 2]
```diff
@@ -221,6 +221,7 @@ func (r *PEXReactor) Receive(chID byte, src Peer, msgBytes []byte) {
 		// 2) limit the output size
 		if r.config.SeedMode {
 			r.SendAddrs(src, r.book.GetSelectionWithBias(biasToSelectNewPeers))
+			src.FlushStop()
```
Comment (melekes) [inline p2p/pex/pex_reactor.go]: so we're calling FlushStop() and after that Stop() in StopPeerGracefully()? Won't it make sense to have a Flush() func and leave stopping to OnStop?

pros:
- no code duplication
- separation of concerns

File: p2p/conn/connection.go [hunk 3]
```diff
@@ -200,15 +202,56 @@ func (c *MConnection) OnStart() error {
...
+	// we close it @ recvRoutine.
+
+	// c.Stop()
+}
+
+// OnStop implements BaseService
+func (c *MConnection) OnStop() {
+	select {
+	case <-c.quit:
+		// already quit via FlushStop
```
Comment (melekes) [inline p2p/conn/connection.go]: 🤢 see my comment above

File: p2p/pex/pex_reactor.go (hunk 2 above)
Comment (ebuchman) [reply p2p/pex/pex_reactor.go]: The problem is, to ensure there's no races or new messages that get queued and not sent, we need the Flush func to stop the service so that all queued sends can be flushed and no new ones are concurrently created. I couldn't think of a better way to do it.

One alternative was to create a FlushSend method which waited until a send was actually flushed out on the conn, but that was more complicated than this solution.

Comment (melekes) [reply p2p/pex/pex_reactor.go]: > there's no races or new messages that get queued and not sent, we need the Flush func to stop the service so that all queued sends can be flushed and no new ones are concurrently created.

Yeah, right. But why do you care about them. Here we only care about flushing one msg ^^^.

Comment (ebuchman) [reply p2p/pex/pex_reactor.go]: Because we don't want to have a race condition in the code? We can't safely call `sendSomePacketMsgs` directly until the sendRoutine has exited otherwise we'll have a real race condition.

I agree with you in principle, but it would take some rearchitecting of the code to do what we want safely here

File: p2p/conn/connection.go [hunk 4]
```diff
@@ -200,15 +202,56 @@ func (c *MConnection) OnStart() error {
 	return nil
 }
 
-// OnStop implements BaseService
-func (c *MConnection) OnStop() {
+// FlushStop replicates the logic of OnStop,
+// but flushes all pending msgs before closing the connection.
```
Comment (jaekwon) [inline p2p/conn/connection.go]: // This method ensures that all successful .Send() calls will get flushed before closing

File: p2p/conn/connection.go [hunk 5]
```diff
@@ -85,6 +85,7 @@ type MConnection struct {
 	config        MConnConfig
 
 	quit       chan struct{}
+	done       chan struct{}
```
Comment (jaekwon) [inline p2p/conn/connection.go]: I'd comment here that closing .quit "causes" .done to close.  Not obvious, but nice convention.

File: p2p/conn/connection.go [hunk 6]
```diff
@@ -200,15 +202,56 @@ func (c *MConnection) OnStart() error {
 	return nil
 }
 
-// OnStop implements BaseService
-func (c *MConnection) OnStop() {
+// FlushStop replicates the logic of OnStop,
+// but flushes all pending msgs before closing the connection.
+func (c *MConnection) FlushStop() {
```
Comment (jaekwon) [inline p2p/conn/connection.go]: Is this safe with concurrent/repeated FlushStop calls?  The Service Stop/OnStop mechanism ensures that OnStop only gets called once.  Not so here.

File: p2p/conn/connection.go [hunk 7]
```diff
@@ -200,15 +202,56 @@ func (c *MConnection) OnStart() error {
...
 	c.BaseService.OnStop()
```
[the remark this answers is not in the document]
Comment (ebuchman) [reply p2p/conn/connection.go]: No because we need to run some logic before the Conn is closed in OnStop

**Comment by ebuchman** [comment]
@melekes @jaekwon addressed all feedback - PTAL.

I had to add some extra logic to ensure FlushStop is not called more than once.

Also realized the seed node was disconnecting from all peers as soon as it received a pex-request, rather than just inbound peers.
