### PR TITLE
rpc: fix RPC client doesn't handle url's without ports

### LINKED ISSUE #5407: RPC: does not handle url's without ports
RPC does not handle URL's without ports. 

Below is a simple test

```go
func TestMakeHTTPDialerURL(t *testing.T) {
	remote := "https://foo-bar.com"

	u, err := newParsedURL(remote)
	require.NoError(t, err)
	dialFn, err := makeHTTPDialer(remote)
	require.Nil(t, err)

	addr, err := dialFn(u.Scheme, u.GetHostWithPath())
	require.NoError(t, err)
	require.NotNil(t, addr)
}
```

The error: 

```sh
dial tcp: address foo-bar.com: missing port in address
```

### PR DESCRIPTION
**Pull request by JayT106**
padding service name as port when URL doesn't have port info, so `net.dialer` will lookup the default port for the service.

Closes #5407

### CODE REVIEW

File: rpc/jsonrpc/client/http_json_client.go [hunk 1]
```diff
@@ -378,7 +380,13 @@ func makeHTTPDialer(remoteAddr string) (func(string, string) (net.Conn, error),
 	}
 
 	dialFn := func(proto, addr string) (net.Conn, error) {
-		return net.Dial(protocol, u.GetDialAddress())
+		var timeout = 10 * time.Second
+		if !u.isUnixSocket && strings.LastIndex(u.Host, ":") == -1 {
```
Comment (alexanderbez) [inline rpc/jsonrpc/client/http_json_client.go:384]: Do you have an example of input here and resulting output?

Comment (JayT106) [reply rpc/jsonrpc/client/http_json_client.go:384]: `https://foo-bar.com` -> `foo-bar.com:https`
`http://foo-bar.com` -> `foo-bar.com:http`
`unix:///tmp/test` -> 'unix:///tmp/test' (because it's UnixSocket)

ref: https://cs.opensource.google/go/go/+/refs/tags/go1.16.4:src/net/ipsock.go;drc=193d5141318d65cea310d995258288bd000d734c;l=248

Comment (alexanderbez) [reply rpc/jsonrpc/client/http_json_client.go:384]: And why do we need to do this?

Comment (JayT106) [reply rpc/jsonrpc/client/http_json_client.go:384]: These fixes just try to tackle the issue @marbar3778 posted. We can just close it if we think the current error message is good enough. But the user needs to aware they need to input the URL address with port info.

Comment (JayT106) [reply rpc/jsonrpc/client/http_json_client.go:384]: in `newParsedURL` function.if we do `url.Parse` with `https://foo-bar.com`.
We will get `url.Scheme` = "https", `url.Host` = "foo-bar.com"
So under this input case, It's not able to connect to the remote due to a missing port.
Therefore I am padding the protocol at the end of the Host, and then the socket will look up the default port for the protocol.

Comment (alexanderbez) [reply rpc/jsonrpc/client/http_json_client.go:384]: I will let @marbar3778 approve this one 👍

Comment (marbar3778) [reply rpc/jsonrpc/client/http_json_client.go:384]: I think this makes things a bit easier for when a user is connecting to a URL. What is the norm here? Should the application handle this instead?

File: rpc/jsonrpc/client/http_json_client.go [hunk 2]
```diff
@@ -370,6 +371,7 @@ func makeHTTPDialer(remoteAddr string) (func(string, string) (net.Conn, error),
 	}
 
 	protocol := u.Scheme
+	var padding = u.Scheme
```
Comment (tychoish) [inline rpc/jsonrpc/client/http_json_client.go:374]: I would use the walrus (`:=`) here just for consistency.

File: rpc/jsonrpc/client/http_json_client_test.go [hunk 3]
```diff
@@ -84,3 +84,18 @@ func Test_parsedURL(t *testing.T) {
 		})
 	}
 }
+
+func TestMakeHTTPDialerURL(t *testing.T) {
+	remotes := []string{"https://foo-bar.com", "http://foo-bar.com"}
```
Comment (tychoish) [inline rpc/jsonrpc/client/http_json_client_test.go:89]: do we want to add other kinds of protocols and/or test error cases?

**Review by tychoish — CHANGES_REQUESTED** [review]

File: rpc/jsonrpc/client/http_json_client_test.go (hunk 3 above)
Comment (JayT106) [reply rpc/jsonrpc/client/http_json_client_test.go:89]: @tychoish what other kinds of protocols we will use in the HTTP client?

Comment (JayT106) [reply rpc/jsonrpc/client/http_json_client_test.go:89]: I can add some error cases.

Comment (JayT106) [reply rpc/jsonrpc/client/http_json_client_test.go:89]: Added 2 error test cases.

**Comment by tessr** [comment]
@JayT106 is this ready for another review? @tychoish do you want to re-review?

**Review by tychoish — APPROVED** [review]

**Review by cmwaters — APPROVED** [review]

**Comment by gibson042** [comment]
I think this ticket should be reopened, since cb63ab4ac0e5dd2b8ddae1b14e3cf7de403630fc apparently never landed on the `main` branch. See also parallel issue https://github.com/cometbft/cometbft/issues/1902 .
