### PR TITLE
Backport: #6494

### LINKED ISSUE #6488: `/status` endpoint returns empty `version`
**Tendermint version**:
Tetsted with `v0.34.4`, `v0.34.5`, `v0.34.6`, `v0.34.7`, `v0.34.8`, `v0.34.9`, `v0.34.10`

**ABCI app**: 
Tendermint Docker file - No app

**Environment**:
Tendermint Docker

**What happened**:
When calling the `/status` endpoint the returned `node_info.version` is always empty if Tendermint version if `>= 0.34.4`

**What you expected to happen**:
The `node_info.version` should return either the Tendermint version or the checksum of the version

**Have you tried the latest version**: yes/no
Yes

**How to reproduce it** (as minimally and precisely as possible):
1. Start a Tendermint Docker container 
2. Query the `/status` endpoint

### PR DESCRIPTION
**Pull request by marbar3778**
Add version back to versions, but allow it to be overridden via a ldflag.

Reason:

Many users are not setting the ldflag causing issues with tooling that relies on it (cosmjs)

closes #6488

### CODE REVIEW

File: version/version.go [hunk 1]
```diff
@@ -1,12 +1,14 @@
 package version
 
 var (
-	// TMCoreSemVer is the current version of Tendermint Core.
-	// It's the Semantic Version of the software.
-	TMCoreSemVer string
```
Comment (cmwaters) [inline version/version.go:6]: Could other apps be relying on this? Would this be an API breaking change?

Comment (marbar3778) [reply version/version.go:6]: ah I can change the name back for the backport, good call

File: CHANGELOG_PENDING.md [hunk 2]
```diff
@@ -12,6 +12,8 @@ Friendly reminder, we have a [bug bounty program](https://hackerone.com/tendermi
 
 - Apps
 
+    - [Version] \#6494 `TMCoreSemVer` is not required to be set ldflags in order to set version in Tendermint.
```
Comment (marbar3778) [inline CHANGELOG_PENDING.md:15]:
```suggestion
    - [Version] \#6494 `TMCoreSemVer` is not required to be set as a ldflag any longer.
```

**Review by cmwaters — APPROVED** [review]
