### PR TITLE
rpc/lib/client & server: try to conform to JSON-RPC 2.0 spec

### LINKED ISSUE #2949: Responses to "subscribe" sent over WebSocket don't conform to RPC 2.0 specification
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.25.0-0c9c3292

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

kvstore

**Environment**:
- **OS** (e.g. from /etc/os-release):

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

- **Install tools**:
- **Others**:

**What happened**:

The responses to "subscribe" over websocket are not as expected.

I believe that they are not in conformance with the RPC 2.0 spec.  (I could be wrong about that.)

When the following "subscribe" message is sent over the websocket:

{"jsonrpc":"2.0","method":"subscribe","id":"1","params":["tm.event = 'NewBlock'"]} I get this response:

I get the following response:

{
  "jsonrpc": "2.0",
  "id": "1",
  "result": {}
}

This is as expected, indicating that the message was received and processed without error.  In the above, the "id" value is 1, indicating this is the first request sent.  (I send it immediately after connecting the socket.)

Subsequently, whenever a new block is created, I get a message like this:

{"jsonrpc":"2.0","id":"1#event","result":{"query":"tm.event = 'NewBlock'","data":{"type":"tendermint/event/NewBlock","value":{"block":  ..... (block contents deleted)

I believe this is NOT in accordance with the JSON RPC 2.0 spec.  The id value is set to "1#event', which chokes the javascript RPC library I'm using.  (https://github.com/jershell/simple-jsonrpc-js)

I think I get the idea behind this - sending the events responding to the subscription request with an id value that can be correlated back to the original request.  But I don't think this is conformant.  The spec says the ID value has to be identical to the request, and that a notification should not contain an ID value.

I was able to work around this by hacking the siimple-jsonrpc-js code to look for responses with id's ending in #event, and convert them into notifications.

Maybe this is how RPC 2.0 is supposed to work?  If so, I'm not seeing that in the spec, and the library I'm using doesn't recognize it.

I do see a related bug request #1099 

**What you expected to happen**:

The events resulting from a subscription request should be sent as NOTIFICATIONs.

**Have you tried the latest version**: yes/no

No.  Latest now appears to be 0.26.4, and I see in the comments that a fix was made to accept integer IDs (I also ran into that one, so that's great.)  I will try to download latest and test against it, but I don't see anything in change log that indicates this has been fixed.

**How to reproduce it** (as minimally and precisely as possible):

Send any valid subscribe message over websocket and then dump out the responses that come back.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

See above.

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by melekes**
Redo of https://github.com/tendermint/tendermint/pull/3858

https://www.jsonrpc.org/specification

What is done in this PR:

    JSONRPCClient: validate that Response.ID matches Request.ID I wanted
    to do the same for the WSClient, but since we're sending events as
    responses, not notifications, checking IDs would require storing
    them in memory indefinitely (and we won't be able to remove them
    upon client unsubscribing because ID is different then).

    Request.ID is now optional. Notification is a Request without an ID.
    Previously "" or 0 were considered as notifications

    Remove #event suffix from ID from an event response (partially fixes
    #2949) ID must be either string, int or null AND must be equal to
    request's ID. Now, because we've implemented events as responses, WS
    clients are tripping when they see Response.ID("0#event") !=
    Request.ID("0"). Implementing events as requests would require a lot
    of time (~ 2 days to completely rewrite WS client and server)

    generate unique ID for each request

    switch to integer IDs instead of "json-client-XYZ"
    id=0 method=/subscribe
    id=0 result=...
    id=1 method=/abci_query
    id=1 result=...

> send events (resulting from /subscribe) as requests+notifications (not
responses)

this will require a lot of work. probably not worth it

* rpc: generate an unique ID for each request
in conformance with JSON-RPC spec

* WSClient: check for unsolicited responses

* fix golangci warnings

* save commit

* fix errors

* remove ID from responses from subscribe
Fixes #2949

* clients are safe for concurrent access

* tm-bench: switch to int ID

* fixes after my own review

* comment out sentIDs in WSClient
see commit body for the reason

* remove body.Close
it will be closed automatically

* stop ws connection outside of write/read routines
also, use t.Rate in tm-bench indexer when calculating ID

* fix gocritic issues

* [x] Referenced an issue explaining the need for the change
* [x] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

File: rpc/lib/server/ws_handler.go [hunk 1]
```diff
@@ -0,0 +1,448 @@
...
+					wsc.Logger.Info("Client closed the connection")
+				} else {
+					wsc.Logger.Error("Failed to read request", "err", err)
+				}
+				wsc.Stop()
+				close(wsc.readRoutineQuit)
+				return
+			}
+
+			err = json.Unmarshal(in, request)
```
Comment (golangcibot) [inline rpc/lib/server/ws_handler.go]: SA1014: json.Unmarshal expects to unmarshal into a pointer, but the provided value is not a pointer (from `staticcheck`)

File: rpc/lib/server/http_uri_handler.go [hunk 2]
```diff
@@ -0,0 +1,196 @@
...
+		expectingInt = true
+	case reflect.String:
+		expectingString = true
+	case reflect.Slice:
+		expectingByteSlice = rt.Elem().Kind() == reflect.Uint8
+	}
+
+	if isIntString && expectingInt {
+		qarg := `"` + arg + `"`
+		// jsonStringToArg
```
Comment (melekes) [inline rpc/lib/server/http_uri_handler.go]:
```suggestion
```

File: rpc/lib/server/ws_handler.go [hunk 3]
```diff
@@ -0,0 +1,448 @@
...
+	if wsc.ctx != nil {
+		return wsc.ctx
+	}
+	wsc.ctx, wsc.cancel = context.WithCancel(context.Background())
+	return wsc.ctx
+}
+
+// Read from the socket and subscribe to or unsubscribe from events
+func (wsc *wsConnection) readRoutine() {
+	var request types.RPCRequest
```
Comment (NicolasMahe) [inline rpc/lib/server/ws_handler.go]: a bug has been introduced by moving this variable outside of the for loop (because it is used in the defer function to display the `request.ID` in the error message).
When one ws client (one connection) wants to subscribe to multiple events (multiple call to `Subscribe` method), the ws messages always contains the ID for the last subscriber.
previous place where this variable was declared: https://github.com/tendermint/tendermint/pull/4141/files#diff-692f910080346cdb0d29bfba93c21569L701

@antho1404 is working on a fix and should create a PR soon.

Comment (melekes) [reply rpc/lib/server/ws_handler.go]: Good catch! Thanks

Comment (NicolasMahe) [reply rpc/lib/server/ws_handler.go]: PR in progress: https://github.com/tendermint/tendermint/pull/4406
