### PR TITLE
types: prevent temporary power overflows on validator updates

### LINKED ISSUE #4164: Temporal Overflows when Updating validator set
**Tendermint version**: `97222eb90fc4b2882fe1859a665f2c84764c4b58`

**What happened**: When adding a new validator that temporarily exceedes the `TotalMaxVotingPower` limit, Tendermint crashes

**What you expected to happen**: The validator should be added to the set

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Say we have the following:
`validator_1` with power = `TotalMaxVotingPower - 1` and
`validator_2` with power = `1`

If you want to update the powers so that:
`validator_2` with power = `TotalMaxVotingPower - 1` and
`validator_1` with power = `1`

Tendermint might end up panicking due to Power Overflow

### PR DESCRIPTION
**Pull request by gchaincl**
Closes #4164

### CODE REVIEW

File: types/validator_set.go [hunk 1]
```diff
@@ -399,13 +399,14 @@ func verifyUpdates(
...
-		overflow := updatedTotalVotingPower > MaxTotalVotingPower
-		if overflow {
-			err = fmt.Errorf(
-				"failed to add/update validator %v, total voting power would exceed the max allowed %v",
-				valUpdate, MaxTotalVotingPower)
-			return 0, 0, err
-		}
+	}
+
+	overflow := updatedTotalVotingPower > MaxTotalVotingPower
```
Comment (ebuchman) [inline types/validator_set.go]: is it possible the voting power actually overflowed the int64 during the for loop tho?

Comment (ancazamfir) [reply types/validator_set.go]: Yes, this will overflow and panic. Here is the stacktrace:
goroutine 54 [running]:
testing.tRunner.func1(0xc000556100)
	/usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:830 +0x392
panic(0x168c320, 0xc0000cd230)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/tendermint/tendermint/types.(*ValidatorSet).updateTotalVotingPower(0xc0004af770)
	/Users/ancaz/go/src/github.com/tendermint/tendermint/types/validator_set.go:268 +0x17e
github.com/tendermint/tendermint/types.(*ValidatorSet).updateWithChangeSet(0xc0004af770, 0xc0004afe00, 0x5, 0x5, 0x1, 0x5, 0x0)
	/Users/ancaz/go/src/github.com/tendermint/tendermint/types/validator_set.go:571 +0x20a
github.com/tendermint/tendermint/types.(*ValidatorSet).UpdateWithChangeSet(...)
	/Users/ancaz/go/src/github.com/tendermint/tendermint/types/validator_set.go:593
github.com/tendermint/tendermint/types.applyChangesToValSet(0xc000556100, 0xc0004af770, 0xc000063d30, 0x3, 0x3)
	/Users/ancaz/go/src/github.com/tendermint/tendermint/types/validator_set_test.go:1112 +0x17d
github.com/tendermint/tendermint/types.verifyValSetUpdatePriorityOrder(0xc000556100, 0xc0004af770, 0xc000476180, 0x5, 0x5, 0x1eab140, 0x0, 0x0, 0xc000476200, 0x5, ...)
	/Users/ancaz/go/src/github.com/tendermint/tendermint/types/validator_set_test.go:1160 +0x1df
github.com/tendermint/tendermint/types.TestValSetUpdatePriorityOrderTests(0xc000556100)
	/Users/ancaz/go/src/github.com/tendermint/tendermint/types/validator_set_test.go:1148 +0x2f7
testing.tRunner(0xc000556100, 0x18ccdf0)
	/usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:916 +0x35a

**Comment by melekes** [comment]
> Sorry for coming late with this but I was not aware of the proposed changes. I don't think this is the proper fix. There is also a similar problem when we try to remove high power validators and add/ update validators with resulting high power.

Are you saying this PR hasn't solved the problem? Or hasn't solved anything at all? Or that there's a similar bug present?

**Comment by ancazamfir** [comment]
>> Sorry for coming late with this but I was not aware of the proposed changes. I don't think this is the proper fix. There is also a similar problem when we try to remove high power validators and add/ update validators with resulting high power.
>
>Are you saying this PR hasn't solved the problem? Or hasn't solved anything at all? Or that there's a similar bug present?

It solved one particular test case but introduced an overflow/ panic for updates for others. I wrote one test to show this on master.
The other problem that was uncovered by @gchaincl 's issue was a similar case that involves removals (e.g. remove one val with high power and add a new one. That is still not fixed and I have another test for that that fails (before and after the changes for this issue). I will open a PR to fix all these and first commit will be some tests.

**Comment by gchaincl** [comment]
Thanks for pointing this out @ancazamfir let me know if I can help
