### PR TITLE
libs/os: EnsureDir now returns IO errors and checks file type

### LINKED ISSUE #5839: libs/os: EnsureDir erroneously assumes that the only error that happens is os.IsNotExist but doesn't handle any other failures
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
At tip aef1ac7ba5d5f2d73cba706d2d23fafeeb73d8ef

**What happened**:
I audited the code in lib/os and noticed this code
https://github.com/tendermint/tendermint/blob/aef1ac7ba5d5f2d73cba706d2d23fafeeb73d8ef/libs/os/os.go#L36-L44

If there is any other failure that occurs e.g. permission errors, messed up partition, too many files open it return a nil error :-(

**What you expected to happen**:
It should report errors

**Have you tried the latest version**: yes/no
Yes

**How to reproduce it** (as minimally and precisely as possible):
This code will exhibit the failure and serve as a regression test
```go
func TestEnsureDir(t *testing.T) {
        tmpDir, err := ioutil.TempDir(".", "ensure-dir")
        if err != nil {
                t.Fatal(err)
        }
        defer os.RemoveAll(tmpDir)

        // 1. Make a sub-directory and set its permissions to be
        // non-writable.
        subDir := filepath.Join(tmpDir, "sub1")
        if err := os.MkdirAll(subDir, 0755); err != nil {
                t.Fatal(err)
        }
        // R-*-* *-*-* *-*-*
        if err := os.Chmod(subDir, 0400); err != nil {
                t.Fatal(err)
        }
        // Revert the permissions to ensure a successful deletion.
        defer os.Chmod(subDir, 0755)

        if err := tmos.EnsureDir(filepath.Join(subDir, "child"), 0755); err == nil {
                t.Fatal("Unexpectedly passed")
        }
}
```

**Anything else we need to know**:
Yes, that code could be refactored for early returns or use a switch and it'll make failures obvious and trivial to catch for the future
```go
func EnsureDir(dir string, mode os.FileMode) error {
        _, err := os.Stat(dir)
        if !os.IsNotExist(err) {
                return err
        }

        // Otherwise now try MkdirAll it.
        return os.MkdirAll(dir, mode)
}
```

### PR DESCRIPTION
**Pull request by erikgrinaker**
Fixes #5839.

### CODE REVIEW

**Review by marbar3778 — APPROVED** [review]
LGTM

File: libs/os/os.go [hunk 1]
```diff
@@ -33,12 +33,19 @@ func Exit(s string) {
...
-		}
+	info, err := os.Stat(dir)
+	if err != nil && !os.IsNotExist(err) {
+		return fmt.Errorf("failed to stat %q: %w", dir, err)
+	}
+	if info != nil && !info.IsDir() {
+		return fmt.Errorf("path %q already exists as a non-directory", dir)
+	}
+	err = os.MkdirAll(dir, mode)
+	if err != nil {
```
Comment (alexanderbez) [inline libs/os/os.go:47]: nit: can make this a one-liner

**Review by alexanderbez — APPROVED** [review]
