### PR TITLE
mempool: return error when WAL fails

### LINKED ISSUE #2319: mempool: return error when WAL fails
`mempool.CheckTx` (used by the `BroadcastTxAsync` and `BroadcastTxSync` RPC handlers) does not return an error when it fails to persist the transaction.

https://github.com/tendermint/tendermint/blob/9e940b95ad4d27efab60d0d49278db5acb2a3b7e/mempool/mempool.go#L248-L260

As a result, transactions can be lost and there is no good way to learn about it.

I did not reproduce it for real, judging by the code so could have possibly overlooked something, looking for your feedback.

### PR DESCRIPTION
**Pull request by melekes**
Closes #2319

### CODE REVIEW

File: mempool/clist_mempool.go [hunk 1]
```diff
@@ -253,7 +255,23 @@ func (mem *CListMempool) CheckTx(tx types.Tx, cb func(*abci.Response), txInfo Tx
...
-	// CACHE
+	// NOTE: writing to the WAL and calling proxy must be done before adding tx
+	// to the cache. otherwise, if either of them fails, next time CheckTx is
+	// called with tx, ErrTxInCache will be returned without tx being checked at
+	// all even once.
+	if mem.wal != nil {
+		// TODO: Notify administrators when WAL fails
+		_, err := mem.wal.Write(append([]byte(tx), newline...))
+		if err != nil {
+			return fmt.Errorf("wal.Write: %w", err)
```
Comment (marbar3778) [inline mempool/clist_mempool.go:266]: It might still be beneficial to keep the error log here.

Comment (melekes) [reply mempool/clist_mempool.go:266]: the error will be logged by the caller

**Review by marbar3778 — APPROVED** [review]
utACK

**Review by erikgrinaker — APPROVED** [review]
