### PR TITLE
Fix TX payload for DO testnets

### LINKED ISSUE #9539: Most transactions in DO testnets get refused
Issue tracked by #9123 and #9333

**Tendermint version**

v0.34.x, v0.37.x, main

**ABCI app**

e2e (dafault in DO testnets)

**Environment**:

DO linux droplet

**What happened**:

Most transactions send by the `test/loadtime` tool get rejected

**What you expected to happen**:

TX should not be rejected

**Have you tried the latest version**

yes

**How to reproduce it** (as minimally and precisely as possible):

Follow the process [here](https://github.com/interchainio/tendermint-testnet/blob/main/README.md)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

N/A

**Config (you can paste only the changes you've made)**:

Default

**node command runtime flags**:

Default

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

N/A

**Anything else we need to know**:

Problem is already root-caused

### PR DESCRIPTION
**Pull request by sergio-mena**
Closes #9539

This PR changes the way the payload is encoded and decoded in the `loadtime` tool.
To make sure only one "=" character appears in the transaction's payload, we:
* First we use protobufs to encode the `Payload` structure
* Then we encode those bytes in (uppercase) hex

As this encoding is less efficient, we need to adjust the padding length in order to obtain the desired transaction length.

The tradeoff here is that the minimum transaction payload is doubled (the space required to store a transaction without padding); but we are not likely to hit this limit anytime soon.

---

#### PR checklist

- [x] Tests written/updated, or no tests needed
- [x] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [x] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

File: test/loadtime/payload/payload.go [hunk 1]
```diff
@@ -37,22 +38,28 @@ func NewBytes(p *Payload) ([]byte, error) {
 	if err != nil {
 		return nil, err
 	}
+	h := []byte(fmt.Sprintf("%X", b))
```
Comment (thanethomson) [inline test/loadtime/payload/payload.go:41]: If we convert the _whole_ payload to hex, won't the reporting tool not be able to interpret the payload?

I'd recommend just converting the padding to hex, using a similar approach to what you've used here:

```golang
func makePadding(size uint64) ([]byte, error) {
    b := make([]byte, (size/2)+1))
    _, err := rand.Read(b)
    if err != nil {
        return nil, err
    }
    p := ([]byte(hex.EncodeToString(b)))[:size]
    return p, nil
}
```

I suspect the `hex.EncodeToString` call will also be more efficient than `fmt.Sprintf`.

Comment (thanethomson) [reply test/loadtime/payload/payload.go:41]: Thinking about this now though, would the rest of the payload data also potentially contain `=` symbols? I suspect it would, if it's binary-encoded.

This means the payload would need to be encoded in a non-binary format, but how do we then reliably decode it using the reporting tool? (Both approaches we have now would result in us sometimes truncating the protobuf message)

Should we perhaps consider changing the payload format to be a plain text-based format? Perhaps just JSON with whitespace at the end for padding?

Comment (sergio-mena) [reply test/loadtime/payload/payload.go:41]: Thanks for the `hex.EncodeToString` suggestion. I'll adapt the PR.

As for encoding only the padding, I thought about it, but that would still be problematic if the protobuf marshalling of our data (timestamp, uuid, size, etc) happens to contain a byte "=". That's why I ended up encoding everything, even if that means the min payload is now doubled in size.

Comment (sergio-mena) [reply test/loadtime/payload/payload.go:41]: > If we convert the whole payload to hex, won't the reporting tool not be able to interpret the payload?

The PR also adapts the unmarshalling (in a symmetric way)

Comment (thanethomson) [reply test/loadtime/payload/payload.go:41]: Ah, I see, that's great then!

**Review by thanethomson — APPROVED** [review]
Nice, thanks @sergio-mena! I ran the code on this branch against a localnet and got:

```
Experiment ID: 8700df95-852e-407b-ac88-9b443ae82007

        Connections: 1
        Rate: 1000
        Size: 1024

        Total Valid Tx: 9000
        Total Negative Latencies: 0
        Minimum Latency: 577.637343ms
        Maximum Latency: 2.222080172s
        Average Latency: 1.232116008s
        Standard Deviation: 422.259864ms

Total Invalid Tx: 0
```

The stats output from the loadtime tool:

```
Parameter,Value,Units
total_time,10.001,seconds
total_txs,9000,count
total_bytes,9216000,bytes
avg_tx_rate,899.939669,transactions per second
avg_data_rate,921538.221460,bytes per second
```

Seems like every tx that was accepted by `broadcast_tx_sync` was found by the reporting tool.

Have you tested this with the E2E app yet? (i.e. in a testnet)

**Comment by sergio-mena** [comment]
> I ran the code on this branch against a localnet and got:

Thanks a lot for testing that!

> Have you tested this with the E2E app yet? (i.e. in a testnet)

Yes... stingy as I am, it has *one* validator and *one* seed node :-D; and, with the code in this PR, 99% of the sent transactions were reported by both Prometheus and the reporting part of loadtime.
