### PR TITLE
Consensus: Fix nondeterministic tests

### LINKED ISSUE #3451: consensus: non-deterministic test failure TestResetTimeoutPrecommitUponNewHeight
```
--- FAIL: TestResetTimeoutPrecommitUponNewHeight (0.22s)
    assertions.go:247: 
                          
	Error Trace:	state_test.go:1382
        
	Error:      	Should be true
        
	Test:       	TestResetTimeoutPrecommitUponNewHeight

```

[build_50471_step_105_container_3.txt](https://github.com/tendermint/tendermint/files/2985991/build_50471_step_105_container_3.txt)

### PR DESCRIPTION
**Pull request by milosevic**
Should fix #3451, #2723 and #3317.

* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [x] Updated CHANGELOG_PENDING.md

### CODE REVIEW

**Comment by milosevic** [comment]
Test `TestResetTimeoutPrecommitUponNewHeight` is simplified so it reduces a risk of timeout failure. Furthermore, timeout we wait for TimeoutEvents is increased, and the timeout value is precisely computed. This should hopefully decrease a chance of non-deterministic test failures.

**Comment by milosevic** [comment]
It seems that some RPC tests are failing.

**Comment by Liamsi** [comment]
The (rpc) test failing here is `TestTx`. Looks like a new test-failure? See the details below:
<details>
<summary> Click for details</summary>

```
--- FAIL: TestTx (0.11s)
    rpc_test.go:357: client 0, case 0
    assertions.go:247: 
                          
	Error Trace:	rpc_test.go:366
        
	Error:      	Expected nil, but got: Tx: response error: RPC error -32603 - Internal error: Tx (98CA6FDCE4D0CDA96C1D26BD8011D1F7A8C5E7FE2C8350836455CA4FCFBAA453) not found
        
	Test:       	TestTx
        
	Messages:   	response error: RPC error -32603 - Internal error: Tx (98CA6FDCE4D0CDA96C1D26BD8011D1F7A8C5E7FE2C8350836455CA4FCFBAA453) not found
        
	            	github.com/tendermint/tendermint/rpc/lib/client.unmarshalResponseBytes
        
	            		/go/src/github.com/tendermint/tendermint/rpc/lib/client/http_client.go:309
        
	            	github.com/tendermint/tendermint/rpc/lib/client.(*JSONRPCClient).Call
        
	            		/go/src/github.com/tendermint/tendermint/rpc/lib/client/http_client.go:156
        
	            	github.com/tendermint/tendermint/rpc/client.(*baseRPCClient).Tx
        
	            		/go/src/github.com/tendermint/tendermint/rpc/client/httpclient.go:305
        
	            	github.com/tendermint/tendermint/rpc/client_test.TestTx
        
	            		/go/src/github.com/tendermint/tendermint/rpc/client/rpc_test.go:361
        
	            	testing.tRunner
        
	            		/usr/local/go/src/testing/testing.go:865
        
	            	runtime.goexit
        
	            		/usr/local/go/src/runtime/asm_amd64.s:1337
        
	            	Tx
        
	            	github.com/tendermint/tendermint/rpc/client.(*baseRPCClient).Tx
        
	            		/go/src/github.com/tendermint/tendermint/rpc/client/httpclient.go:307
        
	            	github.com/tendermint/tendermint/rpc/client_test.TestTx
        
	            		/go/src/github.com/tendermint/tendermint/rpc/client/rpc_test.go:361
        
	            	testing.tRunner
        
	            		/usr/local/go/src/testing/testing.go:865
        
	            	runtime.goexit
        
	            		/usr/local/go/src/runtime/asm_amd64.s:1337
```
</details>

File: consensus/state_test.go [hunk 1]
```diff
@@ -1375,12 +1375,8 @@ func TestResetTimeoutPrecommitUponNewHeight(t *testing.T) {
 	// add precommits
 	signAddVotes(cs1, types.PrecommitType, nil, types.PartSetHeader{}, vs2)
 	signAddVotes(cs1, types.PrecommitType, theBlockHash, theBlockParts, vs3)
-	time.Sleep(5 * time.Millisecond)
 	signAddVotes(cs1, types.PrecommitType, theBlockHash, theBlockParts, vs4)
 
-	rs = cs1.GetRoundState()
-	assert.True(t, rs.TriggeredTimeoutPrecommit)
```
Comment (Liamsi) [inline consensus/state_test.go]: Question: why does it make sense to remove this assertion here?

**Comment by Liamsi** [comment]
I restarted the build and now all tests pass. @milosevic can the [above](https://github.com/tendermint/tendermint/pull/3582#issuecomment-485697008) test failure be directly related to these changes here?

File: consensus/state_test.go (hunk 1 above)
Comment (milosevic) [reply consensus/state_test.go]: This assertion is problematic to ensure consistently due to dependency on scheduler. On the other hand, if I am not wrong, order in which messages are read from the channel respects order in which messages are written. Therefore, process will receive 2f+1 precommits that are not all for v (one is for nil) so TriggeredTimeoutPrecommit would be set to true. So we don't need to assert it. I know that it would be better to still assert to it but I don't know how to do it without sleep and that is ugly and is causing us nondeterministic failures. Does it make sense?

**Comment by milosevic** [comment]
> I restarted the build and now all tests pass. @milosevic can the [above](https://github.com/tendermint/tendermint/pull/3582#issuecomment-485697008) test failure be directly related to these changes here?

The changes I made shouldn't affect rpc tests as functions from common tests are not used there. And I just increase timeouts there.

File: consensus/state_test.go (hunk 1 above)
Comment (Liamsi) [reply consensus/state_test.go]: Makes sense! Ideally, all our unit-tests would not depend on `time.Sleep` at all (or only in the very simplest tests).

File: consensus/common_test.go [hunk 2]
```diff
@@ -351,7 +351,7 @@ func ensureNoNewUnlock(unlockCh <-chan tmpubsub.Message) {
 }
 
 func ensureNoNewTimeout(stepCh <-chan tmpubsub.Message, timeout int64) {
-	timeoutDuration := time.Duration(timeout*5) * time.Nanosecond
+	timeoutDuration := time.Duration(timeout*10) * time.Nanosecond
```
Comment (melekes) [inline consensus/common_test.go]: seems too small for me 😄

Comment (Liamsi) [reply consensus/common_test.go]: Yes, could as well be too small. Only time will tell :-D
