### PR TITLE
rpc: fix panic when `Subscribe` is called

### LINKED ISSUE #4568: WSClient#nextRequestID: invalid memory address or nil pointer dereference
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): v0.33.2

**ABCI app** (name for built-in, URL for self-written if it's publicly available): none

**Environment**:
- **OS** (e.g. from /etc/os-release): mac os
- **Install tools**:
- **Others**:

**What happened**:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4851cf2]goroutine 1 [running]:
github.com/tendermint/tendermint/rpc/lib/client.(*WSClient).nextRequestID(0x0, 0x400ec46)
	/Users/johnzampolin/go/pkg/mod/github.com/tendermint/tendermint@v0.33.2/rpc/lib/client/ws_client.go:261 +0x22
github.com/tendermint/tendermint/rpc/lib/client.(*WSClient).Call(0x0, 0x4fed180, 0xc000d91920, 0x4ced285, 0x9, 0xc000caf8b8, 0xc000046800, 0x580d3c0)
	/Users/johnzampolin/go/pkg/mod/github.com/tendermint/tendermint@v0.33.2/rpc/lib/client/ws_client.go:237 +0x40
github.com/tendermint/tendermint/rpc/lib/client.(*WSClient).Subscribe(...)
	/Users/johnzampolin/go/pkg/mod/github.com/tendermint/tendermint@v0.33.2/rpc/lib/client/ws_client.go:534
github.com/tendermint/tendermint/rpc/client.(*WSEvents).Subscribe(0xc00057e990, 0x4fed180, 0xc000d91920, 0xc000dd85c0, 0xf, 0x4cf9097, 0x15, 0x0, 0x0, 0x0, ...)
	/Users/johnzampolin/go/pkg/mod/github.com/tendermint/tendermint@v0.33.2/rpc/client/httpclient.go:466 +0x153
github.com/cosmos/relayer/relayer.(*Chain).Subscribe(0xc000d95a00, 0x4cf9097, 0x15, 0x4, 0xc000dad678, 0x0, 0x0)
	/Users/johnzampolin/go/src/github.com/cosmos/relayer/relayer/chain.go:161 +0x16b
github.com/cosmos/relayer/cmd.glob..func1(0x57fc220, 0xc000d9d820, 0x2, 0x2, 0x0, 0x0)
	/Users/johnzampolin/go/src/github.com/cosmos/relayer/cmd/start.go:47 +0x24f
github.com/spf13/cobra.(*Command).execute(0x57fc220, 0xc000d9d7c0, 0x2, 0x2, 0x57fc220, 0xc000d9d7c0)
	/Users/johnzampolin/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x57fbf80, 0x404587a, 0x579d680, 0xc000000180)
	/Users/johnzampolin/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/johnzampolin/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/cosmos/relayer/cmd.Execute()
	/Users/johnzampolin/go/src/github.com/cosmos/relayer/cmd/root.go:79 +0x55
main.main()
	/Users/johnzampolin/go/src/github.com/cosmos/relayer/main.go:21 +0x20
exit status 2
```

**What you expected to happen**:
WS subscribing to events works

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
https://github.com/cosmos/relayer/pull/59/files

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by melekes**
but HTTP client is not running.

`Subscribe`, `Unsubscribe(All)` methods return an error now.

Closes #4568
______

For contributor use:

- [x] Wrote tests
- [x] Updated CHANGELOG_PENDING.md
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Updated relevant documentation (`docs/`) and code comments
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

File: rpc/client/event_test.go [hunk 1]
```diff
@@ -28,6 +30,7 @@ func TestHeaderEvents(t *testing.T) {
 	for i, c := range GetClients() {
 		i, c := i, c // capture params
 		t.Run(reflect.TypeOf(c).String(), func(t *testing.T) {
+
```
Comment (tessr) [inline rpc/client/event_test.go]: nit: spurious newline

File: rpc/client/examples_test.go [hunk 2]
```diff
@@ -20,7 +21,7 @@ func ExampleHTTP_simple() {
 	rpcAddr := rpctest.GetConfig().RPC.ListenAddress
 	c, err := client.NewHTTP(rpcAddr, "/websocket")
 	if err != nil {
-		panic(err)
+		log.Fatal(err)
```
Comment (tessr) [inline rpc/client/examples_test.go]: are these functions test helpers? examples? something else?

File: rpc/client/httpclient.go [hunk 3]
```diff
@@ -37,6 +37,27 @@ indefinitely until successful.
 Request batching is available for JSON RPC requests over HTTP, which conforms to
 the JSON RPC specification (https://www.jsonrpc.org/specification#batch). See
 the example for more details.
+
+Example:
```
Comment (tessr) [inline rpc/client/httpclient.go]: nice :)

File: rpc/client/httpclient.go [hunk 4]
```diff
@@ -459,10 +488,17 @@ func (w *WSEvents) OnStop() {
 // Subscribe implements EventsClient by using WSClient to subscribe given
 // subscriber to query. By default, returns a channel with cap=1. Error is
 // returned if it fails to subscribe.
+//
 // Channel is never closed to prevent clients from seeing an erroneus event.
```
Comment (tessr) [inline rpc/client/httpclient.go]: while you're in here, could you fix this spelling? it should be "erroneous" 😁

File: rpc/client/examples_test.go (hunk 2 above)
Comment (melekes) [reply rpc/client/examples_test.go]: https://golang.org/pkg/log/#Fatal

stdlib functions. I prefer to use them in example tests instead of panics.

Comment (tessr) [reply rpc/client/examples_test.go]: Sorry, I meant the functions in this file. I know we're trying to "reduce panics" but since log.Fatal functions just like a panic, I'm wondering if there's a better alternative. 

For example, if these functions are test helpers, we could pass a `t.Testing` in and then call `t.Fatal`.

Comment (melekes) [reply rpc/client/examples_test.go]: Normally, we'd use t.Testing, but since these are example tests https://blog.golang.org/examples, log.Fatal is preferable (that's what stdlib is using https://golang.org/src/net/http/httptest/example_test.go)

Comment (tessr) [reply rpc/client/examples_test.go]: Cool, that answers my original question--I wasn't sure if they were examples, test helpers, or actual tests.

File: rpc/client/event_test.go (hunk 1 above)
Comment (melekes) [inline rpc/client/event_test.go]:
```suggestion
```

File: rpc/client/httpclient.go (hunk 4 above)
Comment (melekes) [inline rpc/client/httpclient.go]:
```suggestion
// Channel is never closed to prevent clients from seeing an erroneous event.
```
