### PR TITLE
lite2: manage witness dropout

### LINKED ISSUE #4346: lite2: remove a witness if it misses N headers
We'll be cross-checking each header with all witnesses. If some witness refuses to give us a header, we should increment some counter, so when the number reaches say 50 failed attempts (meaning a witness did not give us 50 headers in a row), we remove it from the list completely and forget about it.

### PR DESCRIPTION
**Pull request by cmwaters**
Closes #4346

As opposed to what was requested, the current implementation just removes the witness if there is no response after the `maxRetryAttempts`. We can discuss further implementing a counter for each witness and removing them after a set maxCounter is reached but this would be rather verbose. 
 

* [x] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

### CODE REVIEW

File: lite2/errors.go [hunk 1]
```diff
@@ -2,6 +2,7 @@ package lite
 
 import (
 	"fmt"
+	"github.com/tendermint/tendermint/lite2/provider"
```
Comment (golangcibot) [inline lite2/errors.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

File: lite2/client.go [hunk 2]
```diff
@@ -916,11 +916,25 @@ func (c *Client) compareNewHeaderWithWitnesses(h *types.SignedHeader) error {
...
+	for i := 0; i < len(c.witnesses); i++ {
+		witness := c.witnesses[i]
 
 		// 2. Fetch the header.
-		altH, err := witness.SignedHeader(h.Height)
-		if err != nil {
+		altH, err := c.signedHeaderFromWitness(witness, h.Height)
+		switch err.(type) {
+		case nil:
+			break
```
Comment (melekes) [inline lite2/client.go]: why do we break? shouldn't we continue and compare hashes?

File: lite2/client.go [hunk 3]
```diff
@@ -916,11 +916,25 @@ func (c *Client) compareNewHeaderWithWitnesses(h *types.SignedHeader) error {
...
+		case ErrWitnessNonResponsive: // remove witness
```
Comment (melekes) [inline lite2/client.go]: not clear to me why we need this block? if witness is not responsive, we should just remove it and continue with the rest of the witnesses

File: lite2/client.go [hunk 4]
```diff
@@ -1110,6 +1124,26 @@ func (c *Client) validatorSetFromPrimary(height int64) (*types.ValidatorSet, err
 	return c.validatorSetFromPrimary(height)
 }
 
+func (c *Client) signedHeaderFromWitness(witness provider.Provider, height int64) (*types.SignedHeader, error) {
+	for attempt := uint16(1); attempt <= c.maxRetryAttempts; attempt++ {
```
Comment (melekes) [inline lite2/client.go]: can we extract this code into a function (smth like `signedHeaderFrom(p Provider, ...)`)?

Comment (cmwaters) [reply lite2/client.go]: Yes, we can try. You mean to also merge it with the signedHeaderFromPrimary. I thought about earlier but just decided to implement it like this first

File: lite2/client.go (hunk 3 above)
Comment (cmwaters) [reply lite2/client.go]: Do we need to make the distinction between errors or regardless of the errors should we then remove it and continue

File: lite2/client.go (hunk 4 above)
Comment (melekes) [reply lite2/client.go]: > You mean to also merge it with the signedHeaderFromPrimary

yes

Comment (cmwaters) [reply lite2/client.go]: Okay yes I can do that

**Comment by melekes** [comment]
> no response after the maxRetryAttempts

this will drastically increase the new header verification time. not sure we want that

File: lite2/client.go (hunk 3 above)
Comment (melekes) [reply lite2/client.go]: regardless

**Comment by cmwaters** [comment]
> > no response after the maxRetryAttempts
> 
> this will drastically increase the new header verification time. not sure we want that

This depends on what we set the maxRetryAttempts at. But I agree. If it is 10 than that is a couple of minutes per witness. I can only suggest that we don't retry but move on to the next witness immediately.

File: lite2/client.go (hunk 4 above)
Comment (cmwaters) [reply lite2/client.go]: In hindsight, I don't think that these two should be merged because they are from distinct data structures and they have different processes surrounding how non responsiveness should be dealt with
