### PR TITLE
Ensure that peers can't change IP of known nodes

### LINKED ISSUE #1581: p2p/addrbook: failed sanity check "Cant add old address to new bucket"
Just saw the following on gaia-5001

```
I[05-16|12:43:07.097] Saving AddrBook to file                      module=p2p book=/root/.gaiad/config/addrbook.json size=74
I[05-16|12:43:07.100] Ensure peers                                 module=p2p numOutPeers=9 numInPeers=8 numDialing=0 numToDial=1
I[05-16|12:43:07.100] Will dial address                            module=p2p addr=4d927e3403668b22d751cd892fe7430d30a90ae7@108.28.150.189:46656
I[05-16|12:43:07.100] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{35.184.182.143:46656} 30b45459e4881680c0ef1750fde136fefa6c3b98 out}"
I[05-16|12:43:07.100] Dialing peer                                 module=p2p address=4d927e3403668b22d751cd892fe7430d30a90ae7@108.28.150.189:46656
E[05-16|12:43:07.266] Failed Sanity Check! Cant add old address to new bucket module=p2p book=/root/.gaiad/config/addrbook.json ka="&{Addr:678503e6c8f50db7279c7da3cb9b072aac4bc0d5@35.193.188.125:46656 Src:b0dd378c3fbc4c156cd6d302a799f0d2e4227201@159.89.121.174:46656 Attempts:0 LastAttempt:2018-05-16 11:03:52.639711442 +0000 UTC LastSuccess:2018-05-16 11:03:52.639711442 +0000 UTC BucketType:2 Buckets:[37]}" bucket=192
E[05-16|12:43:07.266] Failed Sanity Check! Cant add old address to new bucket module=p2p book=/root/.gaiad/config/addrbook.json ka="&{Addr:30b45459e4881680c0ef1750fde136fefa6c3b98@35.184.182.143:46656 Src:b0dd378c3fbc4c156cd6d302a799f0d2e4227201@159.89.121.174:46656 Attempts:0 LastAttempt:2018-05-16 11:02:04.187007528 +0000 UTC LastSuccess:2018-05-16 11:02:04.187007528 +0000 UTC BucketType:2 Buckets:[56]}" bucket=192
```

### PR DESCRIPTION
**Pull request by ValarDragon**
Closes #1581

This fixes the error in #1581, and also documents the purpose of this line. It ensures that if a peer tells us an address we know about, whose ID is the same as our current ID, we ignore it. 

This removes the previous case where the ID's matched, but the IP's did not, which could yield a potential overwrite of the IP associated with the address later on. (This then would yield an eclipse attack) 

This was _not_ a vulnerability before though, thanks to a defensive check here https://github.com/tendermint/tendermint/blob/master/p2p/pex/addrbook.go#L522)

I did not include a test with this code, because the relevant defensive test did not return an error but instead logged an error.

The code which one can use to manually test this against the previous code is:
```
func Test1581(t *testing.T) {
        fname := createTempFileName("addrbook_test")
        defer deleteTempFile(fname)

        addr, err := p2p.NewNetAddressString("678503e6c8f50db7279c7da3c$
        require.Nil(t, err)
        src, err := p2p.NewNetAddressString("b0dd378c3fbc4c156cd6d302a7$
        require.Nil(t, err)

        book := NewAddrBook(fname, true)
        book.SetLogger(log.TestingLogger())
        err = book.AddAddress(addr, src)
        require.Nil(t, err)
        book.MarkAttempt(addr)
        book.MarkGood(addr.ID)

        // Double check that adding a peer again doesn't error
        err = book.AddAddress(addr, src)
        require.Nil(t, err)

        // Try changing ip but keeping the same node id. (change it to $
        addr2, err := p2p.NewNetAddressString("678503e6c8f50db7279c7da3$
        require.Nil(t, err)
        err = book.AddAddress(addr2, src)
        require.Nil(t, err)
}
```
If you see a logged error after running `pex$ go test -run 1581 -v` a few times, the error is present.

### CODE REVIEW

**Comment by ValarDragon** [comment]
Sure I can change that!

File: p2p/pex/addrbook.go [hunk 1]
```diff
@@ -627,7 +629,9 @@ func (a *addrBook) addAddress(addr, src *p2p.NetAddress) error {
 	}
 
 	bucket := a.calcNewBucket(addr, src)
-	a.addToNewBucket(ka, bucket)
+	if err := a.addToNewBucket(ka, bucket); err != nil {
+		return err
+	}
 	return nil
```
Comment (xla) [inline p2p/pex/addrbook.go]:
```suggestion
	return a.addToNewBucket(ka, bucket)
```

This can be shorten to this.

File: p2p/pex/addrbook_test.go [hunk 2]
```diff
@@ -589,6 +589,53 @@ func TestMultipleAddrBookAddressSelection(t *testing.T) {
...
+	require.Nil(t, err)
+	book.MarkAttempt(peerRealAddr)
+	book.MarkGood(peerRealAddr.ID)
+
+	// Double check that adding a peer again doesn't error
+	err = book.AddAddress(peerRealAddr, src)
+	require.Nil(t, err)
+
+	// Try changing ip but keeping the same node id. (change 1.1.1.1 to 2.2.2.2)
+	// This should just be ignored, and not error.
```
Comment (ValarDragon) [inline p2p/pex/addrbook_test.go:630]: Maybe sending you peer's with the same ID but different IP should be deemed as malicious behaviour / worth lowering your peer score for?

Its tricky since you can't tell which peer sent you the correct IP.

Figured I should flag this in case its worth further discussion in a separate issue. (I don't think it blocks this, since we're still maintaining the old functionality atm)

Comment (xla) [reply p2p/pex/addrbook_test.go:630]: This sounds more suited to be discussed outside of this PR, maybe open up an issue with the open question?

File: p2p/pex/addrbook.go (hunk 1 above)
Comment (ValarDragon) [reply p2p/pex/addrbook.go]: Thanks! changed it =)

File: p2p/pex/addrbook_test.go (hunk 2 above)
Comment (ValarDragon) [reply p2p/pex/addrbook_test.go:630]: Will do!

File: p2p/pex/addrbook.go [hunk 3]
```diff
@@ -629,7 +629,9 @@ func (a *addrBook) addAddress(addr, src *p2p.NetAddress) error {
 	}
 
 	bucket := a.calcNewBucket(addr, src)
-	a.addToNewBucket(ka, bucket)
+	if err := a.addToNewBucket(ka, bucket); err != nil {
```
Comment (melekes) [inline p2p/pex/addrbook.go]:
```suggestion
	return a.addToNewBucket(ka, bucket)
```

File: p2p/pex/errors.go [hunk 4]
```diff
@@ -14,6 +14,15 @@ func (err ErrAddrBookNonRoutable) Error() string {
 	return fmt.Sprintf("Cannot add non-routable address %v", err.Addr)
 }
 
+type ErrAddrBookOldAddressNewBucket struct {
```
Comment (melekes) [inline p2p/pex/errors.go:18]:
```suggestion
type errAddrBookOldAddressNewBucket struct {
```

File: p2p/pex/errors.go [hunk 5]
```diff
@@ -14,6 +14,15 @@ func (err ErrAddrBookNonRoutable) Error() string {
...
+	Addr     *p2p.NetAddress
+	BucketId int
+}
+
+func (err ErrAddrBookOldAddressNewBucket) Error() string {
```
Comment (melekes) [inline p2p/pex/errors.go:23]:
```suggestion
func (err errAddrBookOldAddressNewBucket) Error() string {
```

File: p2p/pex/addrbook.go [hunk 6]
```diff
@@ -466,19 +466,18 @@ func (a *addrBook) getBucket(bucketType byte, bucketIdx int) map[string]*knownAd
...
 // Adds ka to new bucket. Returns false if it couldn't do it cuz buckets full.
 // NOTE: currently it always returns true.
-func (a *addrBook) addToNewBucket(ka *knownAddress, bucketIdx int) {
-	// Sanity check
+func (a *addrBook) addToNewBucket(ka *knownAddress, bucketIdx int) error {
+	// Consistency check to ensure we don't add an already known address
 	if ka.isOld() {
-		a.Logger.Error("Failed Sanity Check! Cant add old address to new bucket", "ka", ka, "bucket", bucketIdx)
-		return
+		return ErrAddrBookOldAddressNewBucket{ka.Addr, bucketIdx}
```
Comment (melekes) [inline p2p/pex/addrbook.go:524]:
```suggestion
		return errAddrBookOldAddressNewBucket{ka.Addr, bucketIdx}
```

File: p2p/pex/errors.go [hunk 7]
```diff
@@ -15,6 +15,17 @@ func (err ErrAddrBookNonRoutable) Error() string {
 	return fmt.Sprintf("Cannot add non-routable address %v", err.Addr)
 }
 
+type errAddrBookOldAddressNewBucket struct {
+	Addr     *p2p.NetAddress
+	BucketID int
+}
+
+func (err errAddrBookOldAddressNewBucket) Error() string {
+	return fmt.Sprintf("Failed consistency check!"+
```
Comment (melekes) [inline p2p/pex/errors.go:24]:
```suggestion
	return fmt.Sprintf("failed consistency check!"+
```

File: p2p/pex/addrbook_test.go (hunk 2 above)
Comment (ebuchman) [reply p2p/pex/addrbook_test.go:630]: I feel like there may have been some initial motivation to allow the IP address associated with an ID to change. One could imaging rebooting a node eg on AWS or otherwise and keeping the same config data (ie. ID) but getting a new IP. Would such a case still be accounted for? Would such a peer now be treated as malicious?

Comment (ValarDragon) [reply p2p/pex/addrbook_test.go:630]: This is definitely really tricky to handle correctly. (I've been having trouble writing the issue, due to me having unclear thoughts on any particular solution idea)

In the code as of this PR, AddAddress would ignore the new node with a different IP. I think this means it would only send messages to the old IP. However noone is marked malicious. 

If we wanted to support this, we'd have to authenticate the incoming connection via secret connection before updating the IP, and maybe have an update methon on the address book.
