### PR TITLE
autofile: resolve relative paths

### LINKED ISSUE #2649: Make autofile resolve absolute paths
When sharing a runtime with Tendermint and in testing it can be convenient to start Tendermint in a test directory. However after initialising a subsequent `os.Chdir` can make autofile fail if it was initialised with a relative path. Although this is somewhat 'as designed' I can't see a time when it wouldn't be preferable to have it resolve the path at the time the `Group` or `Autofile` is created: https://github.com/tendermint/tendermint/blob/master/libs/autofile/group.go#L78

`filepath.Abs()` would do the trick.

This comes up with the WAL in particular, where if you change directory in an unrelated area you get a consensus failure because the wal cannot be written. It would be useful not to have to sanitise tests of `os.Chdir`

### PR DESCRIPTION
**Pull request by erikgrinaker**
Fixes #2649. Does this warrant a changelog entry?

* [x] Referenced an issue explaining the need for the change
* [x] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [x] ~Updated CHANGELOG_PENDING.md~

### CODE REVIEW

**Comment by melekes** [comment]
> Does this warrant a changelog entry?

Of course!

File: libs/autofile/autofile_test.go [hunk 1]
```diff
@@ -3,26 +3,34 @@ package autofile
 import (
 	"io/ioutil"
 	"os"
+	"path"
```
Comment (melekes) [inline libs/autofile/autofile_test.go]: better to use filepath - it's more cross-platform

**Comment by erikgrinaker** [comment]
> > Does this warrant a changelog entry?
> 
> Of course!

Looks like this is only used for the WAL, and the WAL path is explicitly resolved on startup anyway, so this is sort of moot. May as well merge this, but don't see a point in adding it to the changelog, since there should not be any user-visible changes.
