### PR TITLE
tools/tmbench: Bounds checking for txSize.

### LINKED ISSUE #2409: [tm-bench] runtime error: slice bounds out of range
tendermint version: 0.23.1-9e940b95

Steps to reproduce:

[vagrant@dev tm-bench]$tm-bench -T 10 -r 10 -s 39 localhost:26657
panic: runtime error: slice bounds out of range

goroutine 13 [running]:
main.generateTx(0x0, 0x0, 0x27, 0xf7ec95a0bcd06a05, 0x11c84eadb4a4a45b, 0x20, 0xc4200fcb00, 0xc420705d58)
	/home/vagrant/gocode/src/github.com/tendermint/tendermint/tools/tm-bench/transacter.go:266 +0x263
main.(*transacter).sendLoop(0xc42055ea00, 0x0)
	/home/vagrant/gocode/src/github.com/tendermint/tendermint/tools/tm-bench/transacter.go:165 +0x2fb
created by main.(*transacter).Start
	/home/vagrant/gocode/src/github.com/tendermint/tendermint/tools/tm-bench/transacter.go:82 +0x186

### PR DESCRIPTION
**Pull request by WALL-E**
Fixes #2409

### CODE REVIEW

**Comment by WALL-E** [comment]
update commit: improving test cases

File: tools/tm-bench/main.go [hunk 1]
```diff
@@ -68,6 +68,14 @@ Examples:
 		fmt.Printf("Running %ds test @ %s\n", durationInt, flagSet.Arg(0))
 	}
 
+	if txSize < 40 {
+		fmt.Fprintln(
+			os.Stderr,
+			"txSize must be greater than or equal to 40.",
```
Comment (melekes) [inline tools/tm-bench/main.go]: `The size of a transaction must be ...`

Users are not aware of txSize (only tm-bench developers know what txSize is!)

**Comment by WALL-E** [comment]
@melekes I fixed it
