### PR TITLE
blockchain/v2: fix excessive CPU usage due to spinning on closed channels

### LINKED ISSUE #4687: blockchain/v2: high CPU usage
**Tendermint version** ee9545e97196201318df610d258582dd34c29f60

The `v2` blockchain reactor uses 100% CPU, even after switching to consensus. The `v1` reactor uses close to 0% CPU.

To reproduce:

```diff
--- a/networks/local/localnode/config-template.toml
+++ b/networks/local/localnode/config-template.toml
@@ -1,2 +1,5 @@
 [rpc]
 laddr = "tcp://0.0.0.0:26657"
+
+[fastsync]
+version = "v2"
```

```sh
$ rm -rf build/node*; make build-linux && make build-docker-localnode && make localnet-start
```

### PR DESCRIPTION
**Pull request by erikgrinaker**
The event loop uses a `select` on multiple channels. However, reading from a closed channel in Go always yields the channel's zero value. The processor and scheduler close their channels when done, and since these channels are always ready to receive, the event loop keeps spinning on them.

This changes `routine.terminate()` to not close the channel, and also removes `stopDemux` and instead uses `events` channel closure to signal event loop termination.

Fixes #4687.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@brapse You may want to have a look at this as well.

File: blockchain/v2/reactor.go [hunk 1]
```diff
@@ -302,23 +300,25 @@ func (r *BlockchainReactor) demux() {
 	var lastRate = 0.0
 	var lastHundred = time.Now()
 
-	var (
```
Comment (melekes) [inline blockchain/v2/reactor.go:305]: I personally prefer var. We should agree on something instead of changing back / forth

Comment (erikgrinaker) [reply blockchain/v2/reactor.go:305]: I don’t mind the var, this was to put the defer statements after the variables they apply to. We can either have four var blocks or put all defers at the end.
