### PR TITLE
rpc: fix encoding of block_results responses

### LINKED ISSUE #8583: Avoid unnecessary "Sum" field and duplication in pubkey serialization to JSON
The interface CosmJS is expecting for public keys from a few versions ago is

```ts
interface RpcPubkey {
  readonly type: string;
  /** base64 encoded */
  readonly value: string;
}
```

with types like `tendermint/PubKeyEd25519`. It seems like the response has changed in two ways: the type identifier was changed to `tendermint.crypto.PublicKey_Ed25519` and we now get a structure like this:

```
"validator_updates": [
  {
    "pub_key": {
      "Sum": {
        "type": "tendermint.crypto.PublicKey_Ed25519",
        "value": {
          "ed25519": "0kNlxBMpm+5WtfHIG1xsWatOXTKPLtmSqn3EiEIDZeI="
        }
      }
    },
    "power": "11418237"
  },
```

(see https://rpc.cosmos.network/block_results?height=10539773).

I wonder where this `Sum` field is coming from and why it is in the JSON. Also why is "ed25519" duplicated in a value and the value key?

Would it be possible to design this JSON once and then test against a defined JSON output in order to guarantee API stability?

### PR DESCRIPTION
**Pull request by creachadair**
Fixes #8583.

The block results include validator updates in ABCI protobuf format, which does
not encode "correctly" according to the expected Amino style RPC clients expect.

- Write a regression test for this issue.
- Add JSON marshaling overrides for ABCI ValidatorUpdate messages.

This should be backported into v0.35.x, but I will handle that manually because a lot of this plumbing has changed at tip and Mergify will make a dog's breakfast of it.

### CODE REVIEW

File: rpc/coretypes/responses_test.go [hunk 1]
```diff
@@ -33,3 +41,45 @@ func TestStatusIndexer(t *testing.T) {
...
+  "consensus_param_updates": null
+}`, wantKey))))
+
+	bits, err := json.Marshal(rsp)
+	if err != nil {
+		t.Fatalf("Encoding block result: %v", err)
+	}
+	if diff := cmp.Diff(buf.String(), string(bits)); diff != "" {
+		t.Errorf("Marshaled result (-want, +got):\n%s", diff)
+	}
```
Comment (cmwaters) [inline rpc/coretypes/responses_test.go:84]: Why this and not something like require.Equal(....)

**Review by cmwaters — APPROVED** [review]
Looks good.

Do you want to test unmarshaling for completeness?

File: rpc/coretypes/responses_test.go (hunk 1 above)
Comment (creachadair) [reply rpc/coretypes/responses_test.go:84]: Because the output from `require.Equal` doesn't provide a meaningful diff, and most of the test input is not directly relevant to the bug.

**Comment by creachadair** [comment]
> Looks good.
> 
> Do you want to test unmarshaling for completeness?

I have mixed feelings. I only included UnmarshalJSON for symmetry, but we never actually use it (nor in fact do we unmarshal most of these message types). 

There'd be a good argument for dropping those methods entirely, but I didn't want to fold that into this PR.

**Comment by creachadair** [comment]
> > I have mixed feelings. I only included UnmarshalJSON for symmetry, but we never actually use it (nor in fact do we unmarshal most of these message types).
> 
> 
> 
> I thought it was predominantly a convenience function for clients (maybe I'm wrong)

That's true, this one probably makes sense to have even if the others don't. I'll add a test for the other side of it.

**Comment by webmaster128** [comment]
Nice, thank you
